### ISSUE TITLE
NoSuchFieldException: PSWM Entity Render

### ISSUE THREAD

**Issue by BungeeTheCookie** [Parzivail-Modding-Team/ParziStarWarsMod#16]
Hello,
When I am trying to go to another planet in GalactiCraft, I get spammed with this error in my console:

[11:05:35] [Client thread/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:748]: java.lang.NoSuchFieldException: field_78503_V
[11:05:35] [Client thread/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:748]: 	at java.lang.Class.getDeclaredField(Class.java:2062)
[11:05:35] [Client thread/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:748]: 	at micdoodle8.mods.galacticraft.core.client.SkyProviderOverworld.render(SkyProviderOverworld.java:115)
[11:05:35] [Client thread/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:748]: 	at net.minecraft.client.renderer.RenderGlobal.func_72714_a(RenderGlobal.java:964)
[11:05:35] [Client thread/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:748]: 	at com.parzi.starwarsmod.rendering.helper.PSWMEntityRenderer.func_78471_a(PSWMEntityRenderer.java:958)
[11:05:35] [Client thread/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:748]: 	at com.parzi.starwarsmod.rendering.helper.PSWMEntityRenderer.func_78480_b(PSWMEntityRenderer.java:1481)
[11:05:35] [Client thread/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:748]: 	at net.minecraft.client.Minecraft.func_71411_J(Minecraft.java:1001)
[11:05:35] [Client thread/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:748]: 	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:898)
[11:05:35] [Client thread/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:748]: 	at net.minecraft.client.main.Main.main(SourceFile:148)
[11:05:35] [Client thread/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:748]: 	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
[11:05:35] [Client thread/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:748]: 	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
[11:05:35] [Client thread/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:748]: 	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
[11:05:35] [Client thread/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:748]: 	at java.lang.reflect.Method.invoke(Method.java:483)
[11:05:35] [Client thread/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:748]: 	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
[11:05:35] [Client thread/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:748]: 	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)

How do I fix this?

**Comment by parzivail** [comment]
This issue is fixed in the next update, just hang tight :D

**Comment by BungeeTheCookie** [comment]
Ah ok, awesome! Do you know when it's being released? Thank you for fixing it too. Much appreciated!

**Comment by weastonmiller** [comment]
@BungeeTheCookie Worst case scenario end of the month, but probably before, keep checking back and thanks for bearing with us.

**Comment by BungeeTheCookie** [comment]
Ok, thank you very much for your help!
