### ISSUE TITLE
Crashed in the new beta.

### ISSUE THREAD

**Issue by Hmmkk** [Parzivail-Modding-Team/ParziStarWarsMod#26]
[11:34:19] [main/INFO] [LaunchWrapper]: Loading tweak class name cpw.mods.fml.common.launcher.FMLTweaker
[11:34:19] [main/INFO] [LaunchWrapper]: Using primary tweak class name cpw.mods.fml.common.launcher.FMLTweaker
[11:34:19] [main/INFO] [LaunchWrapper]: Calling tweak class cpw.mods.fml.common.launcher.FMLTweaker
[11:34:19] [main/INFO] [FML]: Forge Mod Loader version 7.99.16.1448 for Minecraft 1.7.10 loading
[11:34:19] [main/INFO] [FML]: Java is Java HotSpot(TM) 64-Bit Server VM, version 1.8.0_25, running on Windows 10:amd64:10.0, installed at C:\Program Files (x86)\Minecraft\runtime\jre-x64\1.8.0_25
[11:34:19] [main/WARN] [FML]: The coremod net.malisis.core.asm.MalisisCorePlugin does not have a MCVersion annotation, it may cause issues with this version of Minecraft
[11:34:19] [main/INFO] [LaunchWrapper]: Loading tweak class name cpw.mods.fml.common.launcher.FMLInjectionAndSortingTweaker
[11:34:19] [main/INFO] [LaunchWrapper]: Loading tweak class name cpw.mods.fml.common.launcher.FMLDeobfTweaker
[11:34:19] [main/INFO] [LaunchWrapper]: Calling tweak class cpw.mods.fml.common.launcher.FMLInjectionAndSortingTweaker
[11:34:19] [main/INFO] [LaunchWrapper]: Calling tweak class cpw.mods.fml.common.launcher.FMLInjectionAndSortingTweaker
[11:34:19] [main/INFO] [LaunchWrapper]: Calling tweak class cpw.mods.fml.relauncher.CoreModManager$FMLPluginWrapper
[11:34:20] [main/INFO] [FML]: Found valid fingerprint for Minecraft Forge. Certificate fingerprint e3c3d50c7c986df74c645c0ac54639741c90a557
[11:34:20] [main/INFO] [FML]: Found valid fingerprint for Minecraft. Certificate fingerprint cd99959656f753dc28d863b46769f7f8fbaefcfc
[11:34:20] [main/INFO] [LaunchWrapper]: Calling tweak class cpw.mods.fml.relauncher.CoreModManager$FMLPluginWrapper
[11:34:20] [main/INFO] [LaunchWrapper]: Calling tweak class cpw.mods.fml.common.launcher.FMLDeobfTweaker
[11:34:20] [main/INFO] [LaunchWrapper]: Calling tweak class cpw.mods.fml.relauncher.CoreModManager$FMLPluginWrapper
[11:34:20] [main/INFO] [malisiscore]: [ChunkCollisionTransformer] Hook registered for net.minecraft.world.World
[11:34:20] [main/INFO] [malisiscore]: [ChunkCollisionTransformer] Hook registered for net.minecraft.world.World
[11:34:20] [main/INFO] [malisiscore]: [ChunkCollisionTransformer] Hook registered for net.minecraft.item.ItemBlock
[11:34:20] [main/INFO] [malisiscore]: [ChunkCollisionTransformer] Hook registered for net.minecraft.network.NetHandlerPlayServer
[11:34:20] [main/INFO] [malisiscore]: [ChunkBlockTransformer] Hook registered for net.minecraft.world.chunk.Chunk
[11:34:21] [main/INFO] [LaunchWrapper]: Loading tweak class name cpw.mods.fml.common.launcher.TerminalTweaker
[11:34:21] [main/INFO] [LaunchWrapper]: Calling tweak class cpw.mods.fml.common.launcher.TerminalTweaker
[11:34:21] [main/INFO] [LaunchWrapper]: Launching wrapped minecraft {net.minecraft.client.main.Main}
[11:34:21] [main/INFO] [malisiscore]: Found hooks for net.minecraft.world.World (ahb)
[11:34:21] [main/INFO]: Setting user: IanzZ
[11:34:21] [main/INFO] [malisiscore]: Found hooks for net.minecraft.item.ItemBlock (abh)
[11:34:22] [main/INFO] [STDOUT]: [net.minecraft.client.main.Main:main:144]: Completely ignored arguments: [--nativeLauncherVersion, 286]
[11:34:22] [Client thread/INFO]: LWJGL Version: 2.9.1
[11:34:23] [Client thread/INFO] [STDOUT]: [cpw.mods.fml.client.SplashProgress:start:188]: ---- Minecraft Crash Report ----
// Who set us up the TNT?

Time: 1/24/16 11:34 AM
Description: Loading screen debug info

This is just a prompt for computer specs to be printed. THIS IS NOT A ERROR

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- System Details --
Details:
	Minecraft Version: 1.7.10
	Operating System: Windows 10 (amd64) version 10.0
	Java Version: 1.8.0_25, Oracle Corporation
	Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
	Memory: 82745752 bytes (78 MB) / 190124032 bytes (181 MB) up to 523501568 bytes (499 MB)
	JVM Flags: 7 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xmx3092G -XX:+UseConcMarkSweepGC -XX:+CMSIncrementalMode -XX:-UseAdaptiveSizePolicy -Xmn128M -Xmx512M
	AABB Pool Size: 0 (0 bytes; 0 MB) allocated, 0 (0 bytes; 0 MB) used
	IntCache: cache: 0, tcache: 0, allocated: 0, tallocated: 0
	FML: 
	GL info: ' Vendor: 'NVIDIA Corporation' Version: '4.5.0 NVIDIA 353.82' Renderer: 'GeForce GTX 750 Ti/PCIe/SSE2'
[11:34:23] [Client thread/INFO] [MinecraftForge]: Attempting early MinecraftForge initialization
[11:34:23] [Client thread/INFO] [FML]: MinecraftForge v10.13.4.1448 Initialized
[11:34:23] [Client thread/INFO] [FML]: Replaced 183 ore recipies
[11:34:23] [Client thread/INFO] [MinecraftForge]: Completed early MinecraftForge initialization
[11:34:23] [Client thread/INFO] [FML]: Found 0 mods from the command line. Injecting into mod discoverer
[11:34:23] [Client thread/INFO] [FML]: Searching C:\Users\Max\AppData\Roaming\.minecraft\mods for mods
[11:34:27] [Client thread/INFO] [FML]: Forge Mod Loader has identified 12 mods to load
[11:34:27] [Client thread/INFO] [FML]: Attempting connection with missing mods [mcp, FML, Forge, GraviGun, iChunUtil, malisiscore, malisisdoors, moreplayermodels, cfm, starwarsmod, PortalGun, SAO UI] at CLIENT
[11:34:27] [Client thread/INFO] [FML]: Attempting connection with missing mods [mcp, FML, Forge, GraviGun, iChunUtil, malisiscore, malisisdoors, moreplayermodels, cfm, starwarsmod, PortalGun, SAO UI] at SERVER
[11:34:28] [Client thread/INFO]: Reloading ResourceManager: Default, FMLFileResourcePack:Forge Mod Loader, FMLFileResourcePack:Minecraft Forge, FMLFileResourcePack:GraviGun, FMLFileResourcePack:iChunUtil, FMLFileResourcePack:MalisisCore, FMLFileResourcePack:Malisis' Doors, FMLFileResourcePack:MorePlayerModels, FMLFileResourcePack:§9MrCrayfish's Furniture Mod, FMLFileResourcePack:Parzi's Star Wars Mod, FMLFileResourcePack:PortalGun, FMLFileResourcePack:Sword Art Online UI, 3D Sword Pack 2.zip, BB-8 Resource Pack.zip, 23.zip
[11:34:28] [Client thread/WARN]: ResourcePack: ignored non-lowercase namespace: Thumbs.db in C:\Users\Max\AppData\Roaming\.minecraft\resourcepacks\BB-8 Resource Pack.zip
[11:34:28] [Client thread/INFO] [FML]: Processing ObjectHolder annotations
[11:34:28] [Client thread/INFO] [FML]: Found 341 ObjectHolder annotations
[11:34:28] [Client thread/INFO] [FML]: Identifying ItemStackHolder annotations
[11:34:28] [Client thread/INFO] [FML]: Found 0 ItemStackHolder annotations
[11:34:28] [Client thread/INFO] [FML]: Configured a dormant chunk cache size of 0
[11:34:28] [Client thread/INFO] [GraviGun]: [4.0.0-beta] Loading properties.
[11:34:28] [Client thread/INFO] [malisiscore]: Found hooks for net.minecraft.world.chunk.Chunk (apx)
[11:34:28] [Client thread/INFO] [malisiscore]: Registering CloseInventoryMessage for Packet with discriminator 1 in channel malisiscore
[11:34:28] [Client thread/INFO] [malisiscore]: Registering InventoryActionMessage for Packet with discriminator 2 in channel malisiscore
[11:34:28] [Client thread/INFO] [malisiscore]: Registering OpenInventoryMessage for Packet with discriminator 3 in channel malisiscore
[11:34:28] [Client thread/INFO] [malisiscore]: Registering UpdateInventorySlotsMessage for Packet with discriminator 4 in channel malisiscore
[11:34:28] [Client thread/INFO] [malisiscore]: Registering ChunkBlockMessage for Packet with discriminator 5 in channel malisiscore
[11:34:28] [Client thread/INFO] [malisiscore]: Registering SyncerMessage for Packet with discriminator 6 in channel malisiscore
[11:34:28] [Client thread/INFO] [malisiscore]: Registering DigicodeMessage for Packet with discriminator 1 in channel malisisdoors
[11:34:28] [Client thread/INFO] [malisiscore]: Registering DoorFactoryMessage for Packet with discriminator 2 in channel malisisdoors
[11:34:28] [Client thread/INFO] [malisiscore]: Registering VanishingDiamondFrameMessage for Packet with discriminator 3 in channel malisisdoors
[11:34:28] [Client thread/INFO] [malisiscore]: Replaced ItemDoor by DoorItem in ShapedOreRecipe
[11:34:28] [Client thread/INFO] [malisiscore]: Replaced ItemDoor by DoorItem in StatCrafting
[11:34:28] [Client thread/INFO] [malisiscore]: Replaced ItemDoor by DoorItem in StatCrafting
[11:34:28] [Client thread/INFO] [malisiscore]: Replaced ItemDoor by DoorItem in ShapedOreRecipe
[11:34:28] [Client thread/INFO] [malisiscore]: Replaced ItemDoor by DoorItem in StatCrafting
[11:34:28] [Client thread/INFO] [malisiscore]: Replaced ItemDoor by DoorItem in StatCrafting
[11:34:29] [Client thread/INFO] [StarWarsMod]: Network registered 20 packets!
[11:34:29] [Client thread/INFO] [StarWarsMod]: Configuration loaded!
[11:34:29] [Client thread/INFO] [PortalGun]: [4.0.0-beta-6] Loading properties.
[11:34:29] [Client thread/INFO] [FML]: Applying holder lookups
[11:34:29] [Client thread/INFO] [FML]: Holder lookups applied
[11:34:29] [Client thread/INFO] [FML]: Injecting itemstacks
[11:34:29] [Client thread/INFO] [FML]: Itemstack injection complete
[11:34:29] [Sound Library Loader/INFO] [STDOUT]: [paulscode.sound.SoundSystemLogger:message:69]: 
[11:34:29] [Sound Library Loader/INFO] [STDOUT]: [paulscode.sound.SoundSystemLogger:message:69]: Starting up SoundSystem...
[11:34:29] [Thread-12/INFO] [STDOUT]: [paulscode.sound.SoundSystemLogger:message:69]: Initializing LWJGL OpenAL
[11:34:29] [Thread-12/INFO] [STDOUT]: [paulscode.sound.SoundSystemLogger:message:69]:     (The LWJGL binding of OpenAL.  For more information, see http://www.lwjgl.org)
AL lib: (EE) MMDevApiOpenPlayback: Device init failed: 0x80004005
AL lib: (EE) MMDevApiOpenPlayback: Device init failed: 0x80004005
[11:34:29] [Thread-12/INFO] [STDOUT]: [paulscode.sound.SoundSystemLogger:errorMessage:131]: Error in class 'LibraryLWJGLOpenAL'
[11:34:29] [Thread-12/INFO] [STDOUT]: [paulscode.sound.SoundSystemLogger:errorMessage:132]:     Unable to initialize OpenAL.  Probable cause: OpenAL not supported.
[11:34:29] [Thread-12/INFO] [STDOUT]: [paulscode.sound.SoundSystemLogger:importantMessage:90]:     ERROR MESSAGE:
[11:34:29] [Thread-12/INFO] [STDOUT]: [paulscode.sound.SoundSystemLogger:message:69]:         Could not locate OpenAL library.
[11:34:29] [Thread-12/INFO] [STDOUT]: [paulscode.sound.SoundSystemLogger:importantMessage:90]:     STACK TRACE:
[11:34:29] [Thread-12/INFO] [STDOUT]: [paulscode.sound.SoundSystemLogger:message:69]:         org.lwjgl.openal.AL.create(AL.java:151)
[11:34:29] [Thread-12/INFO] [STDOUT]: [paulscode.sound.SoundSystemLogger:message:69]:         org.lwjgl.openal.AL.create(AL.java:102)
[11:34:29] [Thread-12/INFO] [STDOUT]: [paulscode.sound.SoundSystemLogger:message:69]:         org.lwjgl.openal.AL.create(AL.java:201)
[11:34:29] [Thread-12/INFO] [STDOUT]: [paulscode.sound.SoundSystemLogger:message:69]:         paulscode.sound.libraries.LibraryLWJGLOpenAL.init(LibraryLWJGLOpenAL.java:164)
[11:34:29] [Thread-12/INFO] [STDOUT]: [paulscode.sound.SoundSystemLogger:message:69]:         paulscode.sound.SoundSystem.CommandNewLibrary(SoundSystem.java:1576)
[11:34:29] [Thread-12/INFO] [STDOUT]: [paulscode.sound.SoundSystemLogger:message:69]:         paulscode.sound.SoundSystem.CommandQueue(SoundSystem.java:2572)
[11:34:29] [Thread-12/INFO] [STDOUT]: [paulscode.sound.SoundSystemLogger:message:69]:         paulscode.sound.CommandThread.run(CommandThread.java:121)
[11:34:29] [Client thread/WARN]: File minecraft:sounds/entity/chicken/chirp/03.ogg does not exist, cannot add it to event minecraft:mob.chicken.say
[11:34:29] [Client thread/WARN]: File starwarsmod:sounds/mob/surgical/hit1.ogg does not exist, cannot add it to event starwarsmod:mob.surgical.hit
[11:34:29] [Client thread/WARN]: File starwarsmod:sounds/mob/surgical/die1.ogg does not exist, cannot add it to event starwarsmod:mob.surgical.die
[11:34:29] [Client thread/WARN]: File starwarsmod:sounds/mob/treadwell/hit1.ogg does not exist, cannot add it to event starwarsmod:mob.treadwell.hit
[11:34:29] [Client thread/WARN]: File starwarsmod:sounds/mob/treadwell/die1.ogg does not exist, cannot add it to event starwarsmod:mob.treadwell.die
[11:34:29] [Sound Library Loader/INFO] [STDOUT]: [paulscode.sound.SoundSystemLogger:importantMessage:90]:     ERROR MESSAGE:
[11:34:29] [Sound Library Loader/INFO] [STDOUT]: [paulscode.sound.SoundSystemLogger:message:69]:         Could not locate OpenAL library.
[11:34:29] [Sound Library Loader/INFO] [STDOUT]: [paulscode.sound.SoundSystemLogger:message:69]: 
[11:34:29] [Sound Library Loader/INFO] [STDOUT]: [paulscode.sound.SoundSystemLogger:message:69]: Starting up SoundSystem...
[11:34:30] [Thread-14/INFO] [STDOUT]: [paulscode.sound.SoundSystemLogger:message:69]: Switching to No Sound
[11:34:30] [Thread-14/INFO] [STDOUT]: [paulscode.sound.SoundSystemLogger:message:69]:     (Silent Mode)
[11:34:30] [Client thread/INFO]: Created: 512x512 textures/blocks-atlas
[11:34:30] [Client thread/INFO]: Created: 512x256 textures/items-atlas
[11:34:30] [Sound Library Loader/INFO] [STDOUT]: [paulscode.sound.SoundSystemLogger:message:69]: 
[11:34:30] [Sound Library Loader/INFO]: Sound engine started
[11:34:30] [Client thread/INFO] [StarWarsMod]: ========== Begin Star Wars Mod init() ==========
[11:34:30] [Client thread/INFO] [StarWarsMod]: This is Parzi's Star Wars Mod v1.2.5
[11:34:30] [Client thread/INFO] [StarWarsMod]: Client proxy loaded!
[11:34:30] [Client thread/INFO] [StarWarsMod]: Entities, reporting for duty!
[11:34:30] [Client thread/INFO] [StarWarsMod]: Materials, reporting for duty!
[11:34:30] [Client thread/INFO] [StarWarsMod]: Sequel update! Suck it, JJ!
[11:34:30] [Client thread/INFO] [StarWarsMod]: Items, reporting for duty!
[11:34:30] [Client thread/INFO] [StarWarsMod]: Blocks, reporting for duty!
[11:34:31] [Client thread/INFO] [StarWarsMod]: Provider and World registered for 2
[11:34:31] [Client thread/INFO] [StarWarsMod]: Provider and World registered for 3
[11:34:31] [Client thread/INFO] [StarWarsMod]: Provider and World registered for 4
[11:34:31] [Client thread/INFO] [StarWarsMod]: Provider and World registered for 5
[11:34:31] [Client thread/INFO] [StarWarsMod]: Provider and World registered for 6
[11:34:31] [Client thread/INFO] [StarWarsMod]: Provider and World registered for 7
[11:34:31] [Client thread/INFO] [StarWarsMod]: Provider and World registered for 8
[11:34:31] [Client thread/INFO] [StarWarsMod]: World, reporting for duty!
[11:34:31] [Client thread/INFO] [StarWarsMod]: Recipes, reporting for duty!
[11:34:31] [Client thread/INFO] [StarWarsMod]: Achievements, reporting for duty!
[11:34:31] [Client thread/INFO] [StarWarsMod]: Rendering registered!
[11:34:31] [Client thread/INFO] [StarWarsMod]: =========== End Star Wars Mod init() ===========
[11:34:31] [Client thread/INFO] [FML]: Injecting itemstacks
[11:34:31] [Client thread/INFO] [FML]: Itemstack injection complete
[11:34:32] [Client thread/INFO] [malisiscore]: Loading texture and data for Digital-7 Mono
[11:34:32] [Client thread/INFO] [FML]:   Unknown recipe class! net.malisis.doors.recipe.BigDoorRecipe Modder please refer to net.minecraftforge.oredict.RecipeSorter
[11:34:32] [Client thread/INFO] [FML]: Forge Mod Loader has successfully loaded 12 mods
[11:34:32] [Client thread/INFO]: Reloading ResourceManager: Default, FMLFileResourcePack:Forge Mod Loader, FMLFileResourcePack:Minecraft Forge, FMLFileResourcePack:GraviGun, FMLFileResourcePack:iChunUtil, FMLFileResourcePack:MalisisCore, FMLFileResourcePack:Malisis' Doors, FMLFileResourcePack:MorePlayerModels, FMLFileResourcePack:§9MrCrayfish's Furniture Mod, FMLFileResourcePack:Parzi's Star Wars Mod, FMLFileResourcePack:PortalGun, FMLFileResourcePack:Sword Art Online UI, PortalGunSounds.pak, 3D Sword Pack 2.zip, BB-8 Resource Pack.zip, 23.zip
[11:34:32] [Client thread/WARN]: ResourcePack: ignored non-lowercase namespace: Thumbs.db in C:\Users\Max\AppData\Roaming\.minecraft\resourcepacks\BB-8 Resource Pack.zip
[11:34:32] [Client thread/INFO]: Created: 1024x512 textures/blocks-atlas
[11:34:32] [Client thread/INFO]: Created: 512x512 textures/items-atlas
[11:34:32] [Client thread/INFO] [STDOUT]: [paulscode.sound.SoundSystemLogger:message:69]: 
[11:34:32] [Client thread/INFO] [STDOUT]: [paulscode.sound.SoundSystemLogger:message:69]: SoundSystem shutting down...
[11:34:33] [Client thread/INFO] [STDOUT]: [paulscode.sound.SoundSystemLogger:importantMessage:90]:     Author: Paul Lamb, www.paulscode.com
[11:34:33] [Client thread/INFO] [STDOUT]: [paulscode.sound.SoundSystemLogger:message:69]: 
[11:34:33] [Sound Library Loader/INFO] [STDOUT]: [paulscode.sound.SoundSystemLogger:message:69]: 
[11:34:33] [Sound Library Loader/INFO] [STDOUT]: [paulscode.sound.SoundSystemLogger:message:69]: Starting up SoundSystem...
[11:34:33] [Thread-19/INFO] [STDOUT]: [paulscode.sound.SoundSystemLogger:message:69]: Initializing LWJGL OpenAL
[11:34:33] [Thread-19/INFO] [STDOUT]: [paulscode.sound.SoundSystemLogger:message:69]:     (The LWJGL binding of OpenAL.  For more information, see http://www.lwjgl.org)
[11:34:33] [Thread-19/INFO] [STDOUT]: [paulscode.sound.SoundSystemLogger:message:69]: OpenAL initialized.
[11:34:33] [Client thread/WARN]: File minecraft:sounds/entity/chicken/chirp/03.ogg does not exist, cannot add it to event minecraft:mob.chicken.say
[11:34:33] [Client thread/WARN]: File starwarsmod:sounds/mob/surgical/hit1.ogg does not exist, cannot add it to event starwarsmod:mob.surgical.hit
[11:34:33] [Client thread/WARN]: File starwarsmod:sounds/mob/surgical/die1.ogg does not exist, cannot add it to event starwarsmod:mob.surgical.die
[11:34:33] [Client thread/WARN]: File starwarsmod:sounds/mob/treadwell/hit1.ogg does not exist, cannot add it to event starwarsmod:mob.treadwell.hit
[11:34:33] [Client thread/WARN]: File starwarsmod:sounds/mob/treadwell/die1.ogg does not exist, cannot add it to event starwarsmod:mob.treadwell.die
[11:34:33] [Sound Library Loader/INFO] [STDOUT]: [paulscode.sound.SoundSystemLogger:message:69]: 
[11:34:33] [Sound Library Loader/INFO]: Sound engine started
[11:34:40] [Server thread/INFO]: Starting integrated minecraft server version 1.7.10
[11:34:40] [Server thread/INFO]: Generating keypair
[11:34:40] [Server thread/INFO]: Converting map!
[11:34:40] [Server thread/INFO]: Scanning folders...
[11:34:40] [Server thread/INFO]: Total conversion count is 0
[11:34:40] [Server thread/INFO] [FML]: Injecting existing block and item data into this server instance
[11:34:40] [Server thread/INFO] [FML]: Applying holder lookups
[11:34:40] [Server thread/INFO] [FML]: Holder lookups applied
[11:34:40] [Server thread/INFO] [FML]: Loading dimension 0 (New World) (net.minecraft.server.integrated.IntegratedServer@63535b1f)
[11:34:40] [Server thread/WARN]: Unable to find spawn biome
[11:34:40] [Server thread/INFO] [FML]: Loading dimension 8 (New World) (net.minecraft.server.integrated.IntegratedServer@63535b1f)
[11:34:40] [Server thread/WARN]: Unable to find spawn biome
[11:34:43] [Server thread/INFO] [FML]: Loading dimension 7 (New World) (net.minecraft.server.integrated.IntegratedServer@63535b1f)
[11:34:43] [Server thread/WARN]: Unable to find spawn biome
[11:34:43] [Server thread/INFO] [FML]: Loading dimension 6 (New World) (net.minecraft.server.integrated.IntegratedServer@63535b1f)
[11:34:43] [Server thread/INFO] [FML]: Loading dimension -1 (New World) (net.minecraft.server.integrated.IntegratedServer@63535b1f)
[11:34:43] [Server thread/WARN]: Unable to find spawn biome
[11:34:43] [Server thread/INFO] [FML]: Loading dimension 5 (New World) (net.minecraft.server.integrated.IntegratedServer@63535b1f)
[11:34:43] [Server thread/WARN]: Unable to find spawn biome
[11:34:43] [Server thread/INFO] [FML]: Loading dimension 4 (New World) (net.minecraft.server.integrated.IntegratedServer@63535b1f)
[11:34:43] [Server thread/WARN]: Unable to find spawn biome
[11:34:46] [Server thread/INFO] [FML]: Loading dimension 3 (New World) (net.minecraft.server.integrated.IntegratedServer@63535b1f)
[11:34:46] [Server thread/WARN]: Unable to find spawn biome
[11:34:49] [Server thread/INFO] [FML]: Loading dimension 2 (New World) (net.minecraft.server.integrated.IntegratedServer@63535b1f)
[11:34:49] [Server thread/INFO] [FML]: Loading dimension 1 (New World) (net.minecraft.server.integrated.IntegratedServer@63535b1f)
[11:34:49] [Server thread/INFO] [PortalGun]: [4.0.0-beta-6] Save data does not exist!
[11:34:49] [Server thread/INFO]: Preparing start region for level 0
[11:34:50] [Server thread/INFO]: Preparing spawn area: 22%
[11:34:51] [Server thread/INFO]: Preparing spawn area: 49%
[11:34:52] [Server thread/INFO]: Preparing spawn area: 79%
[11:34:53] [Server thread/INFO] [PortalGun]: [4.0.0-beta-6] World config does not exist, generating.
[11:34:53] [Server thread/INFO]: Changing view distance to 32, from 10
[11:34:54] [Netty IO #1/INFO] [malisiscore]: Found hooks for net.minecraft.network.NetHandlerPlayServer (nh)
[11:34:54] [Netty Client IO #0/INFO] [FML]: Server protocol version 2
[11:34:54] [Netty IO #1/INFO] [FML]: Client protocol version 2
[11:34:54] [Netty IO #1/INFO] [FML]: Client attempting to join with 12 mods : malisiscore@1.7.10-0.14.1,PortalGun@4.0.0-beta-6,FML@7.10.99.99,GraviGun@4.0.0-beta,Forge@10.13.4.1448,malisisdoors@1.7.10-1.13.0,SAO UI@1.0,starwarsmod@1.2.5,mcp@9.05,cfm@3.4.8,iChunUtil@4.2.2,moreplayermodels@1.7.10
[11:34:54] [Netty IO #1/INFO] [FML]: Attempting connection with missing mods [] at CLIENT
[11:34:54] [Netty Client IO #0/INFO] [FML]: Attempting connection with missing mods [] at SERVER
[11:34:54] [Server thread/INFO] [FML]: [Server thread] Server side modded connection established
[11:34:54] [Server thread/INFO]: IanzZ[local:E:a95865ed] logged in with entity id 244 at (-252.5, 70.0, -155.5)
[11:34:54] [Server thread/INFO]: IanzZ joined the game
[11:34:54] [Client thread/INFO] [FML]: [Client thread] Client side modded connection established
[11:35:07] [Server thread/INFO]: IanzZ has just earned the achievement [You've been installed!]

**Comment by parzivail** [comment]
Could you provide the crash log the game saved? This log doesn't actually have a crash in it. Thanks!

**Comment by Hmmkk** [comment]
How do I get to the one the Game Saved?
Sorry Im a Little New To Things Like Crash Reports.

**Comment by parzivail** [comment]
@hmmkk In your `.minecraft` directory, there should be a folder called "crashlogs" or something close to that. find the most recent one and post it here :D

**Comment by Hmmkk** [comment]
Hey sorry i couldnt respond yesterday.
I fixed it today by just lowering my Render distance down by 5
Heres the log anyways!:---- Minecraft Crash Report ----
// Why did you do that?

Time: 1/24/16 11:59 AM
Description: Ticking screen

java.lang.IndexOutOfBoundsException
	at java.nio.Buffer.checkIndex(Buffer.java:540)
	at java.nio.DirectIntBufferU.get(DirectIntBufferU.java:253)
	at net.minecraft.client.renderer.RenderGlobal.func_72712_a(RenderGlobal.java:350)
	at net.minecraft.client.renderer.RenderGlobal.func_72732_a(RenderGlobal.java:294)
	at net.minecraft.client.Minecraft.func_71353_a(Minecraft.java:2216)
	at net.minecraft.client.Minecraft.func_71403_a(Minecraft.java:2146)
	at net.minecraft.client.network.NetHandlerPlayClient.func_147282_a(NetHandlerPlayClient.java:240)
	at net.minecraft.network.play.server.S01PacketJoinGame.func_148833_a(SourceFile:70)
	at net.minecraft.network.play.server.S01PacketJoinGame.func_148833_a(SourceFile:13)
	at net.minecraft.network.NetworkManager.func_74428_b(NetworkManager.java:212)
	at net.minecraft.client.multiplayer.GuiConnecting.func_73876_c(SourceFile:78)
	at net.minecraft.client.Minecraft.func_71407_l(Minecraft.java:1661)
	at net.minecraft.client.Minecraft.func_71411_J(Minecraft.java:973)
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:898)
	at net.minecraft.client.main.Main.main(SourceFile:148)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:483)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)


A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Stacktrace:
	at java.nio.Buffer.checkIndex(Buffer.java:540)
	at java.nio.DirectIntBufferU.get(DirectIntBufferU.java:253)
	at net.minecraft.client.renderer.RenderGlobal.func_72712_a(RenderGlobal.java:350)
	at net.minecraft.client.renderer.RenderGlobal.func_72732_a(RenderGlobal.java:294)
	at net.minecraft.client.Minecraft.func_71353_a(Minecraft.java:2216)
	at net.minecraft.client.Minecraft.func_71403_a(Minecraft.java:2146)
	at net.minecraft.client.network.NetHandlerPlayClient.func_147282_a(NetHandlerPlayClient.java:240)
	at net.minecraft.network.play.server.S01PacketJoinGame.func_148833_a(SourceFile:70)
	at net.minecraft.network.play.server.S01PacketJoinGame.func_148833_a(SourceFile:13)
	at net.minecraft.network.NetworkManager.func_74428_b(NetworkManager.java:212)
	at net.minecraft.client.multiplayer.GuiConnecting.func_73876_c(SourceFile:78)

-- Affected screen --
Details:
	Screen name: net.minecraft.client.multiplayer.GuiConnecting

-- Affected level --
Details:
	Level name: MpServer
	All players: 0 total; []
	Chunk stats: MultiplayerChunkCache: 0, 0
	Level seed: 0
	Level generator: ID 00 - default, ver 1. Features enabled: false
	Level generator options: 
	Level spawn location: World: (8,64,8), Chunk: (at 8,4,8 in 0,0; contains blocks 0,0,0 to 15,255,15), Region: (0,0; contains chunks 0,0 to 31,31, blocks 0,0,0 to 511,255,511)
	Level time: 0 game time, 0 day time
	Level dimension: 0
	Level storage version: 0x00000 - Unknown?
	Level weather: Rain time: 0 (now: false), thunder time: 0 (now: false)
	Level game mode: Game mode: survival (ID 0). Hardcore: false. Cheats: false
	Forced entities: 0 total; []
	Retry entities: 0 total; []
	Server brand: ~~ERROR~~ NullPointerException: null
	Server type: Non-integrated multiplayer server
Stacktrace:
	at net.minecraft.client.multiplayer.WorldClient.func_72914_a(WorldClient.java:373)
	at net.minecraft.client.Minecraft.func_71396_d(Minecraft.java:2444)
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:919)
	at net.minecraft.client.main.Main.main(SourceFile:148)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:483)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)

-- System Details --
Details:
	Minecraft Version: 1.7.10
	Operating System: Windows 10 (amd64) version 10.0
	Java Version: 1.8.0_25, Oracle Corporation
	Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
	Memory: 199556328 bytes (190 MB) / 386891776 bytes (368 MB) up to 523501568 bytes (499 MB)
	JVM Flags: 7 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xmx3092G -XX:+UseConcMarkSweepGC -XX:+CMSIncrementalMode -XX:-UseAdaptiveSizePolicy -Xmn128M -Xmx512M
	AABB Pool Size: 0 (0 bytes; 0 MB) allocated, 0 (0 bytes; 0 MB) used
	IntCache: cache: 0, tcache: 0, allocated: 0, tallocated: 0
	FML: MCP v9.05 FML v7.10.99.99 Minecraft Forge 10.13.4.1448 8 mods loaded, 8 mods active
	States: 'U' = Unloaded 'L' = Loaded 'C' = Constructed 'H' = Pre-initialized 'I' = Initialized 'J' = Post-initialized 'A' = Available 'D' = Disabled 'E' = Errored
	UCHIJA	mcp{9.05} [Minecraft Coder Pack] (minecraft.jar) 
	UCHIJA	FML{7.10.99.99} [Forge Mod Loader] (forge-1.7.10-10.13.4.1448-1.7.10.jar) 
	UCHIJA	Forge{10.13.4.1448} [Minecraft Forge] (forge-1.7.10-10.13.4.1448-1.7.10.jar) 
	UCHIJA	malisiscore{1.7.10-0.14.1} [MalisisCore] (malisiscore-1.7.10-0.14.1.jar) 
	UCHIJA	malisisdoors{1.7.10-1.13.0} [Malisis' Doors] (malisisdoors-1.7.10-1.13.0.jar) 
	UCHIJA	moreplayermodels{1.7.10} [MorePlayerModels] (MorePlayerModels_1.7.10 (2).jar) 
	UCHIJA	cfm{3.4.8} [§9MrCrayfish's Furniture Mod] (MrCrayfishFurnitureModv3.4.8(1.7.10).jar) 
	UCHIJA	starwarsmod{1.2.5} [Parzi's Star Wars Mod] (Parzi's Star Wars Mod v1.2.5-beta.j
