### ISSUE TITLE
Star Fighter Bug

### ISSUE THREAD

**Issue by Jeffreyman101** [Parzivail-Modding-Team/ParziStarWarsMod#42]
I was flying in a star fighter and this happened here is the log Thing:
---- Minecraft Crash Report ----
// Ouch. That hurt :(

Time: 2/6/16 10:30 AM
Description: Ticking entity

java.lang.NullPointerException: Ticking entity
	at com.parzivail.pswm.entities.EntityBlasterBoltBase.func_70184_a(EntityBlasterBoltBase.java:155)
	at net.minecraft.entity.projectile.EntityThrowable.func_70071_h_(SourceFile:192)
	at com.parzivail.pswm.entities.EntityBlasterBoltBase.func_70071_h_(EntityBlasterBoltBase.java:175)
	at net.minecraft.world.World.func_72866_a(World.java:2070)
	at net.minecraft.world.WorldServer.func_72866_a(WorldServer.java:648)
	at net.minecraft.world.World.func_72870_g(World.java:2034)
	at net.minecraft.world.World.func_72939_s(World.java:1887)
	at net.minecraft.world.WorldServer.func_72939_s(WorldServer.java:489)
	at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:636)
	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:547)
	at net.minecraft.server.integrated.IntegratedServer.func_71217_p(IntegratedServer.java:111)
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:427)
	at net.minecraft.server.MinecraftServer$2.run(MinecraftServer.java:685)

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Stacktrace:
	at com.parzivail.pswm.entities.EntityBlasterBoltBase.func_70184_a(EntityBlasterBoltBase.java:155)
	at net.minecraft.entity.projectile.EntityThrowable.func_70071_h_(SourceFile:192)
	at com.parzivail.pswm.entities.EntityBlasterBoltBase.func_70071_h_(EntityBlasterBoltBase.java:175)
	at net.minecraft.world.World.func_72866_a(World.java:2070)
	at net.minecraft.world.WorldServer.func_72866_a(WorldServer.java:648)
	at net.minecraft.world.World.func_72870_g(World.java:2034)

-- Entity being ticked --
Details:
	Entity Type: starwarsmod.blasterXWingBolt (com.parzivail.pswm.entities.EntityXWingBolt)
	Entity ID: 678
	Entity Name: entity.starwarsmod.blasterXWingBolt.name
	Entity's Exact location: 34.27, 72.07, -172.60
	Entity's Block location: World: (34,72,-173), Chunk: (at 2,4,3 in 2,-11; contains blocks 32,0,-176 to 47,255,-161), Region: (0,-1; contains chunks 0,-32 to 31,-1, blocks 0,0,-512 to 511,255,-1)
	Entity's Momentum: 0.64, 0.02, -2.23
Stacktrace:
	at net.minecraft.world.World.func_72939_s(World.java:1887)
	at net.minecraft.world.WorldServer.func_72939_s(WorldServer.java:489)

-- Affected level --
Details:
	Level name: Star Wars Role-play
	All players: 1 total; [EntityPlayerMP['Jeffreyman101'/405, l='Star Wars Role-play', x=-87.30, y=132.05, z=-37.49]]
	Chunk stats: ServerChunkCache: 442 Drop: 0
	Level seed: -1597436854026199261
	Level generator: ID 00 - default, ver 1. Features enabled: false
	Level generator options: 
	Level spawn location: World: (0,0,0), Chunk: (at 0,0,0 in 0,0; contains blocks 0,0,0 to 15,255,15), Region: (0,0; contains chunks 0,0 to 31,31, blocks 0,0,0 to 511,255,511)
	Level time: 0 game time, 0 day time
	Level dimension: 0
	Level storage version: 0x00000 - Unknown?
	Level weather: Rain time: 0 (now: false), thunder time: 0 (now: false)
	Level game mode: ~~ERROR~~ NullPointerException: null
Stacktrace:
	at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:636)
	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:547)
	at net.minecraft.server.integrated.IntegratedServer.func_71217_p(IntegratedServer.java:111)
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:427)
	at net.minecraft.server.MinecraftServer$2.run(MinecraftServer.java:685)

-- System Details --
Details:
	Minecraft Version: 1.7.10
	Operating System: Mac OS X (x86_64) version 10.11.3
	Java Version: 1.8.0_60, Oracle Corporation
	Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
	Memory: 118151880 bytes (112 MB) / 457998336 bytes (436 MB) up to 1060372480 bytes (1011 MB)
	JVM Flags: 5 total; -Xmx1G -XX:+UseConcMarkSweepGC -XX:+CMSIncrementalMode -XX:-UseAdaptiveSizePolicy -Xmn128M
	AABB Pool Size: 0 (0 bytes; 0 MB) allocated, 0 (0 bytes; 0 MB) used
	IntCache: cache: 15, tcache: 0, allocated: 13, tallocated: 95
	FML: MCP v9.05 FML v7.10.99.99 Minecraft Forge 10.13.4.1614 6 mods loaded, 6 mods active
	States: 'U' = Unloaded 'L' = Loaded 'C' = Constructed 'H' = Pre-initialized 'I' = Initialized 'J' = Post-initialized 'A' = Available 'D' = Disabled 'E' = Errored
	UCHIJAAAA	mcp{9.05} [Minecraft Coder Pack] (minecraft.jar) 
	UCHIJAAAA	FML{7.10.99.99} [Forge Mod Loader] (forge-1.7.10-10.13.4.1614-1.7.10.jar) 
	UCHIJAAAA	Forge{10.13.4.1614} [Minecraft Forge] (forge-1.7.10-10.13.4.1614-1.7.10.jar) 
	UCHIJAAAA	customnpcs{1.7.10d} [CustomNpcs] (CustomNPCs_1.7.10d.jar) 
	UCHIJAAAA	mcheli{0.10.7} [MC Helicopter] (mcheli) 
	UCHIJAAAA	starwarsmod{1.2.7} [Parzi's Star Wars Mod] (Parzi's Star Wars Mod v1.2.7.jar) 
	GL info: ~~ERROR~~ RuntimeException: No OpenGL context found in the current thread.
	Profiler Position: N/A (disabled)
	Vec3 Pool Size: 0 (0 bytes; 0 MB) allocated, 0 (0 bytes; 0 MB) used
	Player Count: 1 / 8; [EntityPlayerMP['Jeffreyman101'/405, l='Star Wars Role-play', x=-87.30, y=132.05, z=-37.49]]
	Type: Integrated Server (map_client.txt)
	Is Modded: Definitely; Client brand changed to 'fml,forge'

**Comment by parzivail** [comment]
Fixed in 1.2.8, see #41

**Comment by Jeffreyman101** [comment]
Oh and I Love Your Mod you should add a AT-AT Thanks for fixing this :+1:
