### ISSUE TITLE
Star Fighter Bug [Server Addition]

### ISSUE THREAD

**Issue by Jeffreyman101** [Parzivail-Modding-Team/ParziStarWarsMod#48]
Here is the log :D

---- Minecraft Crash Report ----
// Ouch. That hurt :(

Time: 2/11/16 7:43 PM
Description: Ticking entity

java.lang.NullPointerException: Ticking entity
	at com.parzivail.pswm.entities.EntityBlasterBoltBase.func_70184_a(EntityBlasterBoltBase.java:155)
	at net.minecraft.entity.projectile.EntityThrowable.func_70071_h_(SourceFile:192)
	at com.parzivail.pswm.entities.EntityBlasterBoltBase.func_70071_h_(EntityBlasterBoltBase.java:175)
	at net.minecraft.world.World.func_72866_a(World.java:2070)
	at net.minecraft.world.WorldServer.func_72866_a(WorldServer.java:648)
	at net.minecraft.world.World.func_72870_g(World.java:2034)
	at net.minecraft.world.World.func_72939_s(World.java:1887)
	at net.minecraft.world.WorldServer.func_72939_s(WorldServer.java:489)
	at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:636)
	at net.minecraft.server.dedicated.DedicatedServer.func_71190_q(DedicatedServer.java:334)
	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:547)
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:427)
	at net.minecraft.server.MinecraftServer$2.run(MinecraftServer.java:685)

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Stacktrace:
	at com.parzivail.pswm.entities.EntityBlasterBoltBase.func_70184_a(EntityBlasterBoltBase.java:155)
	at net.minecraft.entity.projectile.EntityThrowable.func_70071_h_(SourceFile:192)
	at com.parzivail.pswm.entities.EntityBlasterBoltBase.func_70071_h_(EntityBlasterBoltBase.java:175)
	at net.minecraft.world.World.func_72866_a(World.java:2070)
	at net.minecraft.world.WorldServer.func_72866_a(WorldServer.java:648)
	at net.minecraft.world.World.func_72870_g(World.java:2034)

-- Entity being ticked --
Details:
	Entity Type: starwarsmod.blasterXWingBolt (com.parzivail.pswm.entities.EntityXWingBolt)
	Entity ID: 548
	Entity Name: entity.starwarsmod.blasterXWingBolt.name
	Entity's Exact location: 449.00, 70.61, 579.21
	Entity's Block location: World: (449,70,579), Chunk: (at 1,4,3 in 28,36; contains blocks 448,0,576 to 463,255,591), Region: (0,1; contains chunks 0,32 to 31,63, blocks 0,0,512 to 511,255,1023)
	Entity's Momentum: 0.32, 0.01, 2.60
Stacktrace:
	at net.minecraft.world.World.func_72939_s(World.java:1887)
	at net.minecraft.world.WorldServer.func_72939_s(WorldServer.java:489)

-- Affected level --
Details:
	Level name: world
	All players: 1 total; [EntityPlayerMP['Jeffreyman101'/368, l='world', x=462.95, y=90.76, z=454.55]]
	Chunk stats: ServerChunkCache: 698 Drop: 0
	Level seed: 5737129693024979369
	Level generator: ID 00 - default, ver 1. Features enabled: true
	Level generator options: 
	Level spawn location: World: (52,76,252), Chunk: (at 4,4,12 in 3,15; contains blocks 48,0,240 to 63,255,255), Region: (0,0; contains chunks 0,0 to 31,31, blocks 0,0,0 to 511,255,511)
	Level time: 57667525 game time, 171896 day time
	Level dimension: 0
	Level storage version: 0x04ABD - Anvil
	Level weather: Rain time: 69688 (now: false), thunder time: 32696 (now: false)
	Level game mode: Game mode: survival (ID 0). Hardcore: false. Cheats: true
Stacktrace:
	at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:636)
	at net.minecraft.server.dedicated.DedicatedServer.func_71190_q(DedicatedServer.java:334)
	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:547)
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:427)
	at net.minecraft.server.MinecraftServer$2.run(MinecraftServer.java:685)

-- System Details --
Details:
	Minecraft Version: 1.7.10
	Operating System: Mac OS X (x86_64) version 10.11.3
	Java Version: 1.8.0_66, Oracle Corporation
	Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
	Memory: 678964376 bytes (647 MB) / 882376704 bytes (841 MB) up to 1908932608 bytes (1820 MB)
	JVM Flags: 0 total; 
	AABB Pool Size: 0 (0 bytes; 0 MB) allocated, 0 (0 bytes; 0 MB) used
	IntCache: cache: 0, tcache: 0, allocated: 13, tallocated: 95
	FML: MCP v9.05 FML v7.10.99.99 Minecraft Forge 10.13.4.1614 7 mods loaded, 7 mods active
	States: 'U' = Unloaded 'L' = Loaded 'C' = Constructed 'H' = Pre-initialized 'I' = Initialized 'J' = Post-initialized 'A' = Available 'D' = Disabled 'E' = Errored
	UCHIJAAAA	mcp{9.05} [Minecraft Coder Pack] (minecraft.jar) 
	UCHIJAAAA	FML{7.10.99.99} [Forge Mod Loader] (forge-1.7.10-10.13.4.1614-1.7.10-universal.jar) 
	UCHIJAAAA	Forge{10.13.4.1614} [Minecraft Forge] (forge-1.7.10-10.13.4.1614-1.7.10-universal.jar) 
	UCHIJAAAA	customnpcs{1.7.10d} [CustomNpcs] (CustomNPCs_1.7.10d.jar) 
	UCHIJAAAA	grapplemod{1.0} [grapplemod] (Grappling-Hook-Mod-1.7.10.jar) 
	UCHIJAAAA	mcheli{0.10.7} [MC Helicopter] (mcheli) 
	UCHIJAAAA	starwarsmod{1.2.7} [Parzi's Star Wars Mod] (Parzi's Star Wars Mod v1.2.7.jar) 
	Profiler Position: N/A (disabled)
	Vec3 Pool Size: 0 (0 bytes; 0 MB) allocated, 0 (0 bytes; 0 MB) used
	Player Count: 1 / 20; [EntityPlayerMP['Jeffreyman101'/368, l='world', x=462.95, y=90.76, z=454.55]]
	Is Modded: Definitely; Server brand changed to 'fml,forge'
	Type: Dedicated Server (map_server.txt)

**Comment by parzivail** [comment]
Fixed in 1.2.8, on the site.
