### ISSUE TITLE
Crash on DIM load client -side

### ISSUE THREAD

**Issue by Momibelle** [Parzivail-Modding-Team/ParziStarWarsMod#5]
Running a Cauldron server with limited plugins, client crashes with this report: 

---- Minecraft Crash Report ----
// I feel sad now :(

Time: 17/11/15 11:40 AM
Description: Ticking screen

java.lang.IllegalArgumentException: Could not get provider type for dimension -100, does not exist
	at net.minecraftforge.common.DimensionManager.getProviderType(DimensionManager.java:148)
	at net.minecraftforge.common.DimensionManager.createProviderFor(DimensionManager.java:302)
	at net.minecraft.world.WorldProvider.func_76570_a(WorldProvider.java:160)
	at net.minecraft.client.multiplayer.WorldClient.<init>(WorldClient.java:54)
	at net.minecraft.client.network.NetHandlerPlayClient.func_147282_a(NetHandlerPlayClient.java:238)
	at net.minecraft.network.play.server.S01PacketJoinGame.func_148833_a(SourceFile:70)
	at net.minecraft.network.play.server.S01PacketJoinGame.func_148833_a(SourceFile:13)
	at net.minecraft.network.NetworkManager.func_74428_b(NetworkManager.java:212)
	at net.minecraft.client.multiplayer.GuiConnecting.func_73876_c(SourceFile:78)
	at net.minecraft.client.Minecraft.func_71407_l(Minecraft.java:1661)
	at net.minecraft.client.Minecraft.func_71411_J(Minecraft.java:973)
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:898)
	at net.minecraft.client.main.Main.main(SourceFile:148)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.multimc.onesix.OneSixLauncher.launchWithMainClass(OneSixLauncher.java:310)
	at org.multimc.onesix.OneSixLauncher.launch(OneSixLauncher.java:394)
	at org.multimc.EntryPoint.listen(EntryPoint.java:170)
	at org.multimc.EntryPoint.main(EntryPoint.java:54)

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Stacktrace:
	at net.minecraftforge.common.DimensionManager.getProviderType(DimensionManager.java:148)
	at net.minecraftforge.common.DimensionManager.createProviderFor(DimensionManager.java:302)
	at net.minecraft.world.WorldProvider.func_76570_a(WorldProvider.java:160)
	at net.minecraft.client.multiplayer.WorldClient.<init>(WorldClient.java:54)
	at net.minecraft.client.network.NetHandlerPlayClient.func_147282_a(NetHandlerPlayClient.java:238)
	at net.minecraft.network.play.server.S01PacketJoinGame.func_148833_a(SourceFile:70)
	at net.minecraft.network.play.server.S01PacketJoinGame.func_148833_a(SourceFile:13)
	at net.minecraft.network.NetworkManager.func_74428_b(NetworkManager.java:212)
	at net.minecraft.client.multiplayer.GuiConnecting.func_73876_c(SourceFile:78)

-- Affected screen --
Details:
	Screen name: net.minecraft.client.multiplayer.GuiConnecting
Stacktrace:
	at net.minecraft.client.Minecraft.func_71407_l(Minecraft.java:1661)
	at net.minecraft.client.Minecraft.func_71411_J(Minecraft.java:973)
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:898)
	at net.minecraft.client.main.Main.main(SourceFile:148)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.multimc.onesix.OneSixLauncher.launchWithMainClass(OneSixLauncher.java:310)
	at org.multimc.onesix.OneSixLauncher.launch(OneSixLauncher.java:394)
	at org.multimc.EntryPoint.listen(EntryPoint.java:170)
	at org.multimc.EntryPoint.main(EntryPoint.java:54)

-- System Details --
Details:
	Minecraft Version: 1.7.10
	Operating System: Windows 10 (amd64) version 10.0
	Java Version: 1.8.0_65, Oracle Corporation
	Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
	Memory: 279624176 bytes (266 MB) / 474480640 bytes (452 MB) up to 1908932608 bytes (1820 MB)
	JVM Flags: 3 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xms512m -Xmx2048m
	AABB Pool Size: 0 (0 bytes; 0 MB) allocated, 0 (0 bytes; 0 MB) used
	IntCache: cache: 0, tcache: 0, allocated: 13, tallocated: 95
	FML: MCP v9.05 FML v7.10.99.99 Minecraft Forge 10.13.4.1448 4 mods loaded, 4 mods active
	States: 'U' = Unloaded 'L' = Loaded 'C' = Constructed 'H' = Pre-initialized 'I' = Initialized 'J' = Post-initialized 'A' = Available 'D' = Disabled 'E' = Errored
	UCHIJA	mcp{9.05} [Minecraft Coder Pack] (minecraft.jar) 
	UCHIJA	FML{7.10.99.99} [Forge Mod Loader] (forge-1.7.10-10.13.4.1448-1.7.10-universal.jar) 
	UCHIJA	Forge{10.13.4.1448} [Minecraft Forge] (forge-1.7.10-10.13.4.1448-1.7.10-universal.jar) 
	UCHIJA	starwarsmod{1.1.1} [Parzi's Star Wars Mod] (Parzi's Star Wars Mod v1.1.1.jar) 
	GL info: ' Vendor: 'Intel' Version: '4.3.0 - Build 10.18.15.4256' Renderer: 'Intel(R) HD Graphics 4600'
	Launched Version: MultiMC5
	LWJGL: 2.9.1
	OpenGL: Intel(R) HD Graphics 4600 GL version 4.3.0 - Build 10.18.15.4256, Intel
	GL Caps: Using GL 1.3 multitexturing.
Using framebuffer objects because OpenGL 3.0 is supported and separate blending is supported.
Anisotropic filtering is supported and maximum anisotropy is 16.
Shaders are available because OpenGL 2.1 is supported.

	Is Modded: Definitely; Client brand changed to 'fml,forge'
	Type: Client (map_client.txt)
	Resource Packs: []
	Current Language: English (US)
	Profiler Position: N/A (disabled)
	Vec3 Pool Size: 0 (0 bytes; 0 MB) allocated, 0 (0 bytes; 0 MB) used
	Anisotropic Filtering: Off (1)

**Comment by parzivail** [comment]
Thanks for the info! We're working on a fix now, it'll be included in the next update, coming soon.

**Comment by Momibelle** [comment]
OK! If you need access to the server to test let me know. I will keep Cauldron running for now.
Anna

**Comment by speedsnip** [comment]
Hi !

Im français so scuse my bad english 😭
i love your mod 😁 But i have too some error when changing world and with saber...

Im waiting for the next update ! thxxxx 😊

**Comment by parzivail** [comment]
@speedsnip hello! thanks for helping out. Could you elaborate a little more about the lightsaber? Does the dimension change crash only when you have one? if so, is it on or off? Thanks!

**Comment by speedsnip** [comment]
Hi again :p 

I <b>crash</b> when i use saber on planet (Tatooine, Yavin...), on get in/out (sorry for my english...)

SEE ATTACHEMENT
[Crash saber.txt](https://github.com/Parzivail-Modding-Team/ParziStarWarsMod/files/41115/Crash.saber.txt)

I have a lot of <b>error</b> all 10 min : 

SEE ATTACHEMENT
[Error ten minutes.txt](https://github.com/Parzivail-Modding-Team/ParziStarWarsMod/files/41118/Error.ten.minutes.txt)

**Comment by speedsnip** [comment]
I have too a <b>Crash</b> when change dimension...

[Crash Dimension.txt](https://github.com/Parzivail-Modding-Team/ParziStarWarsMod/files/41119/Crash.Dimension.txt)

**Comment by parzivail** [comment]
thanks @speedsnip for the crash logs, they were very informative, and we may have found the bug. keep your eyes peeled if it happens again, as what we fixed may not be the only cause. the fix will be published as part of our next release very soon.

**Comment by Momibelle** [comment]
TEMP FIX FOR DIM ISSUES on a Cauldron server

Original issue: crashing/kicked from Cauldron server after leaving the game and trying to log back on (player was on another DIM other than world when logging off). DIM -100 being logged as 'not found' on console.

Temp fix:
Load Multiverse (for 1.7.10), run (we switched to Spigot to test), which unloads all DIMS, then load Cauldron again. -100 DIM is gone. 

: )
Anna

**Comment by speedsnip** [comment]
Merci chère cousine ;)
Mais je n'en suis pas encore la malheureusement vu que Parzi bug je peux continuer a mettre les autres mods et plugins :'(

Vivement la "Next Release" ^^

**Comment by weastonmiller** [comment]
The next release will be out by next friday at the very latest.  Sorry for making you wait especially seeing as how it's been over a month since our last update, we're just making sure all the new content is how we want it and all the fixes are working so we don't have to patch anything right after the release.

**Comment by speedsnip** [comment]
Ok thanks you very much because i like your mod !

**Comment by speedsnip** [comment]
Hello ! When can i next release plz ? :/

**Comment by weastonmiller** [comment]
@speedsnip Sorry for the delay, give us just a few more days and it'll be out

**Comment by weastonmiller** [comment]
This issue is fixed in Update 1.2.0, downloads are [here] (http://parzivail.com/mods/tswm/download.html)

**Comment by weastonmiller** [comment]
This issue is fixed in Update 1.2.0, downloads are [here] (http://parzivail.com/mods/tswm/download.html)

**Comment by speedsnip** [comment]
Thx for this update ^^ but i have always seem error.... :/ (with saber, when in and out...)
