### ISSUE TITLE
When Opening Minecraft I Crashed

### ISSUE THREAD

**Issue by INeedSomeHelpPronto** [Parzivail-Modding-Team/ParziStarWarsMod#55]
PSWM version 1.2.8
Client
When Opening Minecraft I Crashed

Plz Help I Really wanted to try this mod

Here is the Crash Report:

---- Minecraft Crash Report ----
// There are four lights!

Time: 2/14/16 3:42 PM
Description: Initializing game

java.lang.IllegalArgumentException: Failed to register dimension for id 3, One is already registered
	at net.minecraftforge.common.DimensionManager.registerDimension(DimensionManager.java:118)
	at com.parzivail.util.world.WorldUtils.registerDimension(WorldUtils.java:36)
	at com.parzivail.pswm.registry.WorldRegister.registerAll(WorldRegister.java:64)
	at com.parzivail.pswm.StarWarsMod.init(StarWarsMod.java:431)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at cpw.mods.fml.common.FMLModContainer.handleModStateEvent(FMLModContainer.java:532)
	at sun.reflect.GeneratedMethodAccessor3.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at com.google.common.eventbus.EventSubscriber.handleEvent(EventSubscriber.java:74)
	at com.google.common.eventbus.SynchronizedEventSubscriber.handleEvent(SynchronizedEventSubscriber.java:47)
	at com.google.common.eventbus.EventBus.dispatch(EventBus.java:322)
	at com.google.common.eventbus.EventBus.dispatchQueuedEvents(EventBus.java:304)
	at com.google.common.eventbus.EventBus.post(EventBus.java:275)
	at cpw.mods.fml.common.LoadController.sendEventToModContainer(LoadController.java:212)
	at cpw.mods.fml.common.LoadController.propogateStateMessage(LoadController.java:190)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at com.google.common.eventbus.EventSubscriber.handleEvent(EventSubscriber.java:74)
	at com.google.common.eventbus.SynchronizedEventSubscriber.handleEvent(SynchronizedEventSubscriber.java:47)
	at com.google.common.eventbus.EventBus.dispatch(EventBus.java:322)
	at com.google.common.eventbus.EventBus.dispatchQueuedEvents(EventBus.java:304)
	at com.google.common.eventbus.EventBus.post(EventBus.java:275)
	at cpw.mods.fml.common.LoadController.distributeStateMessage(LoadController.java:119)
	at cpw.mods.fml.common.Loader.initializeMods(Loader.java:737)
	at cpw.mods.fml.client.FMLClientHandler.finishMinecraftLoading(FMLClientHandler.java:311)
	at net.minecraft.client.Minecraft.func_71384_a(Minecraft.java:552)
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:878)
	at net.minecraft.client.main.Main.main(SourceFile:148)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Stacktrace:
	at net.minecraftforge.common.DimensionManager.registerDimension(DimensionManager.java:118)
	at com.parzivail.util.world.WorldUtils.registerDimension(WorldUtils.java:36)
	at com.parzivail.pswm.registry.WorldRegister.registerAll(WorldRegister.java:64)
	at com.parzivail.pswm.StarWarsMod.init(StarWarsMod.java:431)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at cpw.mods.fml.common.FMLModContainer.handleModStateEvent(FMLModContainer.java:532)
	at sun.reflect.GeneratedMethodAccessor3.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at com.google.common.eventbus.EventSubscriber.handleEvent(EventSubscriber.java:74)
	at com.google.common.eventbus.SynchronizedEventSubscriber.handleEvent(SynchronizedEventSubscriber.java:47)
	at com.google.common.eventbus.EventBus.dispatch(EventBus.java:322)
	at com.google.common.eventbus.EventBus.dispatchQueuedEvents(EventBus.java:304)
	at com.google.common.eventbus.EventBus.post(EventBus.java:275)
	at cpw.mods.fml.common.LoadController.sendEventToModContainer(LoadController.java:212)
	at cpw.mods.fml.common.LoadController.propogateStateMessage(LoadController.java:190)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at com.google.common.eventbus.EventSubscriber.handleEvent(EventSubscriber.java:74)
	at com.google.common.eventbus.SynchronizedEventSubscriber.handleEvent(SynchronizedEventSubscriber.java:47)
	at com.google.common.eventbus.EventBus.dispatch(EventBus.java:322)
	at com.google.common.eventbus.EventBus.dispatchQueuedEvents(EventBus.java:304)
	at com.google.common.eventbus.EventBus.post(EventBus.java:275)
	at cpw.mods.fml.common.LoadController.distributeStateMessage(LoadController.java:119)
	at cpw.mods.fml.common.Loader.initializeMods(Loader.java:737)
	at cpw.mods.fml.client.FMLClientHandler.finishMinecraftLoading(FMLClientHandler.java:311)
	at net.minecraft.client.Minecraft.func_71384_a(Minecraft.java:552)

-- Initialization --
Details:
Stacktrace:
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:878)
	at net.minecraft.client.main.Main.main(SourceFile:148)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)

-- System Details --
Details:
	Minecraft Version: 1.7.10
	Operating System: Mac OS X (x86_64) version 10.10.5
	Java Version: 1.8.0_65, Oracle Corporation
	Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
	Memory: 181485712 bytes (173 MB) / 535298048 bytes (510 MB) up to 954728448 bytes (910 MB)
	JVM Flags: 1 total; -Xmx1G
	AABB Pool Size: 0 (0 bytes; 0 MB) allocated, 0 (0 bytes; 0 MB) used
	IntCache: cache: 0, tcache: 0, allocated: 0, tallocated: 0
	FML: MCP v9.05 FML v7.10.99.99 Minecraft Forge 10.13.4.1448 Naruto Mod 50 mods loaded, 50 mods active
	States: 'U' = Unloaded 'L' = Loaded 'C' = Constructed 'H' = Pre-initialized 'I' = Initialized 'J' = Post-initialized 'A' = Available 'D' = Disabled 'E' = Errored
	UCHI	mcp{9.05} [Minecraft Coder Pack] (minecraft.jar) 
	UCHI	FML{7.10.99.99} [Forge Mod Loader] (minecraftforge-1.7.10-10.13.4.1448.jar) 
	UCHI	Forge{10.13.4.1448} [Minecraft Forge] (minecraftforge-1.7.10-10.13.4.1448.jar) 
	UCHI	Micdoodlecore{} [Micdoodle8 Core] (minecraft.jar) 
	UCHI	TooManyItems{1.7.10} [TooManyItems] (minecraft.jar) 
	UCHI	mod_ThreadedLighting{1.7.10-1.0} [Threaded Lighting] (minecraft.jar) 
	UCHI	gilded-games-util{1.7.10-1.1} [Gilded Games Utility] (gilded-games-util.jar) 
	UCHI	lightsabers{0.7.1} [Advanced Lightsabers Mod] (AdvancedLightsabers-1.7.10-0.7.2.jar) 
	UCHI	adventurebackpack{1.7.10-0.8b} [Adventure Backpack] (adventurebackpack-1.7.10-0.8c.jar) 
	UCHI	aether{Alpha 1.7.10-1.4} [Aether II] (aether.jar) 
	UCHI	AnimationAPI{1.2.4} [AnimationAPI] (AnimationAPI-1.7.10-1.2.4.jar) 
	UCHI	ArchimedesShips{1.7.10 v1.7.1} [Archimedes' Ships] (ArchimedesShips-1.7.1.jar) 
	UCHI	BuildCraft|Core{7.1.14} [BuildCraft] (buildcraft-7.1.14.jar) 
	UCHI	BuildCraft|Builders{7.1.14} [BC Builders] (buildcraft-7.1.14.jar) 
	UCHI	BuildCraft|Transport{7.1.14} [BC Transport] (buildcraft-7.1.14.jar) 
	UCHI	BuildCraft|Energy{7.1.14} [BC Energy] (buildcraft-7.1.14.jar) 
	UCHI	BuildCraft|Silicon{7.1.14} [BC Silicon] (buildcraft-7.1.14.jar) 
	UCHI	BuildCraft|Robotics{7.1.14} [BC Robotics] (buildcraft-7.1.14.jar) 
	UCHI	BuildCraft|Factory{7.1.14} [BC Factory] (buildcraft-7.1.14.jar) 
	UCHI	chocolateQuest{1.0} [Chocolate Quest] (chocolateQuest-1.7.10-1.1d.jar) 
	UCHI	customnpcs{1.7.10} [CustomNpcs] (CustomNPCs_1.7.10.jar) 
	UCHI	DamageIndicatorsMod{3.2.0} [Damage Indicators] (Damage-Indicators-Mod-1.7.10.jar) 
	UCHI	fossil{1.7.10 Build 7.2.1} [Fossils and Archeology Revival] (Fossils_Archeology_Revival-1.7.10_Build-7.2.1.jar) 
	UCHI	GalacticraftCore{3.0.12} [Galacticraft Core] (GalacticraftCore-1.7-3.0.12.375.jar) 
	UCHI	GalacticraftMars{3.0.12} [Galacticraft Planets] (Galacticraft-Planets-1.7-3.0.12.375.jar) 
	UCHI	GraveStone{2.12.2} [GraveStone] (GraveStone-2.12.2.jar) 
	UCHI	iChunUtil{4.2.2} [iChunUtil] (iChunUtil-4.2.2.jar) 
	UCHI	ninjamod{4.0} [The Ninja Mod] (Jond311s-Ninja-Mod-1.7.10.jar) 
	UCHI	jinryuujrmcore{1.1.16} [JinRyuu's JRMCore] (JRMCore-v1.1.16.jar) 
	UCHI	jcanimation{1.2.4} [JCAnimationAPI] (JurassiCraft-1.4.5.jar) 
	UCHI	llibrary{0.3.3} [LLibrary] (LLibrary-0.3.3-1.7.10.jar) 
	UCHI	jurassicraft{1.4.5} [JurassiCraft] (JurassiCraft-1.4.5.jar) 
	UCHI	Mantle{1.7.10-0.3.2.jenkins184} [Mantle] (Mantle-1.7.10-0.3.2.jar) 
	UCHI	mcanm{1.0.001b_1710} [Minecraft Animated] (mcanm-1.0.001b_1710.jar) 
	UCHI	MCEF{0.6} [Minecraft Chromium Embedded Framework] (MCEF-1.7.10-0.7.jar) 
	UCHI	minecraftstorymodemod{2.0.0} [minecraftstorymodemod] (Mincecraftstorymodemodv2.0.0.zip) 
	UCHI	numina{0.4.0.131} [Numina] (Numina-0.4.0.131.jar) 
	UCHI	powersuits{0.11.0.300} [MachineMuse's Modular Powersuits] (ModularPowersuits-0.11.0.300.jar) 
	UCHI	Morph{0.9.2} [Morph] (Morph-Beta-0.9.2.jar) 
	UCHI	mowziesmobs{1.2.5-undefined} [Mowzie's Mobs] (Mowzie's Mobs-1.2.6.jar) 
	UCHI	MutantCreatures{1.4.9} [Mutant Creatures] (MutantCreatures-1.7.10-1.4.9.jar) 
	UCHI	narutomod{0.3.4} [SEKWAH41's Naruto Mod] (Naruto+Mod+v0.3.4c+-+Pre+release.jar) 
	UCHI	AM{0.1} [Alcohol Mod] (NarutoAnimeMod0.2 - Awakening Of The Uchiha Susanoo.jar) 
	UCHI	jinryuunarutoc{0.5.6} [Naruto C] (NarutoC-v0.5.6.jar) 
	UCHE	starwarsmod{1.2.9} [Parzi's Star Wars Mod] (Parzi's Star Wars Mod v1.2.9.jar) 
	UCHI	PortalGun{4.0.0-beta-6} [PortalGun] (PortalGun-4.0.0-beta-6.jar) 
	UCHI	ReiMinimap{1.7.10} [Rei's Minimap] (Reis-Minimap-Mod-1.7.10.jar) 
	UCHI	sus{4.0.10} [Superheroes Unlimited Mod] (Superheroes Unlimited Mod-1.7.10-4.0.10.jar) 
	UCHI	TConstruct{1.7.10-1.8.8.build988} [Tinkers' Construct] (TConstruct-1.7.10-1.8.8.jar) 
	UCHI	TwilightForest{2.3.7} [The Twilight Forest] (twilightforest-1.7.10-2.3.7.jar) 
	GL info: ' Vendor: 'ATI Technologies Inc.' Version: '2.1 ATI-1.32.25' Renderer: 'AMD Radeon HD 6750M OpenGL Engine'
	Mantle Environment: Environment healthy.
	TConstruct Environment: Environment healthy.
	Launched Version: 1.7.10
	LWJGL: 2.9.1
	OpenGL: AMD Radeon HD 6750M OpenGL Engine GL version 2.1 ATI-1.32.25, ATI Technologies Inc.
	GL Caps: Using GL 1.3 multitexturing.
Using framebuffer objects because ARB_framebuffer_object is supported and separate blending is supported.
Anisotropic filtering is supported and maximum anisotropy is 16.
Shaders are available because OpenGL 2.1 is supported.

	Is Modded: Definitely; Client brand changed to 'fml,forge'
	Type: Client (map_client.txt)
	Resource Packs: []
	Current Language: English (US)
	Profiler Position: N/A (disabled)
	Vec3 Pool Size: 0 (0 bytes; 0 MB) allocated, 0 (0 bytes; 0 MB) used
	Anisotropic Filtering: Off (1)

**Comment by weastonmiller** [comment]
You are using another mod that also uses the dim id 3, you can change and see all of the dim ids we use in our mod in our config which is in your normal minecraft folder. Just change whichever one we have that's using 3 to use some high number and just keep going till it works, it's kinda just trial and error unless you know what all your other mods dim ids are.

**Comment by INeedSomeHelpPronto** [comment]
ok thanks in advance

**Comment by INeedSomeHelpPronto** [comment]
yup that was helpful

**Comment by INeedSomeHelpPronto** [comment]
Now what?

---- Minecraft Crash Report ----
// Ooh. Shiny.

Time: 2/14/16 4:30 PM
Description: Initializing game

java.lang.IllegalArgumentException: Failed to register dimension for id 4, One is already registered
	at net.minecraftforge.common.DimensionManager.registerDimension(DimensionManager.java:118)
	at com.parzivail.util.world.WorldUtils.registerDimension(WorldUtils.java:36)
	at com.parzivail.pswm.registry.WorldRegister.registerAll(WorldRegister.java:65)
	at com.parzivail.pswm.StarWarsMod.init(StarWarsMod.java:431)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at cpw.mods.fml.common.FMLModContainer.handleModStateEvent(FMLModContainer.java:532)
	at sun.reflect.GeneratedMethodAccessor3.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at com.google.common.eventbus.EventSubscriber.handleEvent(EventSubscriber.java:74)
	at com.google.common.eventbus.SynchronizedEventSubscriber.handleEvent(SynchronizedEventSubscriber.java:47)
	at com.google.common.eventbus.EventBus.dispatch(EventBus.java:322)
	at com.google.common.eventbus.EventBus.dispatchQueuedEvents(EventBus.java:304)
	at com.google.common.eventbus.EventBus.post(EventBus.java:275)
	at cpw.mods.fml.common.LoadController.sendEventToModContainer(LoadController.java:212)
	at cpw.mods.fml.common.LoadController.propogateStateMessage(LoadController.java:190)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at com.google.common.eventbus.EventSubscriber.handleEvent(EventSubscriber.java:74)
	at com.google.common.eventbus.SynchronizedEventSubscriber.handleEvent(SynchronizedEventSubscriber.java:47)
	at com.google.common.eventbus.EventBus.dispatch(EventBus.java:322)
	at com.google.common.eventbus.EventBus.dispatchQueuedEvents(EventBus.java:304)
	at com.google.common.eventbus.EventBus.post(EventBus.java:275)
	at cpw.mods.fml.common.LoadController.distributeStateMessage(LoadController.java:119)
	at cpw.mods.fml.common.Loader.initializeMods(Loader.java:737)
	at cpw.mods.fml.client.FMLClientHandler.finishMinecraftLoading(FMLClientHandler.java:311)
	at net.minecraft.client.Minecraft.func_71384_a(Minecraft.java:552)
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:878)
	at net.minecraft.client.main.Main.main(SourceFile:148)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)


A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Stacktrace:
	at net.minecraftforge.common.DimensionManager.registerDimension(DimensionManager.java:118)
	at com.parzivail.util.world.WorldUtils.registerDimension(WorldUtils.java:36)
	at com.parzivail.pswm.registry.WorldRegister.registerAll(WorldRegister.java:65)
	at com.parzivail.pswm.StarWarsMod.init(StarWarsMod.java:431)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at cpw.mods.fml.common.FMLModContainer.handleModStateEvent(FMLModContainer.java:532)
	at sun.reflect.GeneratedMethodAccessor3.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at com.google.common.eventbus.EventSubscriber.handleEvent(EventSubscriber.java:74)
	at com.google.common.eventbus.SynchronizedEventSubscriber.handleEvent(SynchronizedEventSubscriber.java:47)
	at com.google.common.eventbus.EventBus.dispatch(EventBus.java:322)
	at com.google.common.eventbus.EventBus.dispatchQueuedEvents(EventBus.java:304)
	at com.google.common.eventbus.EventBus.post(EventBus.java:275)
	at cpw.mods.fml.common.LoadController.sendEventToModContainer(LoadController.java:212)
	at cpw.mods.fml.common.LoadController.propogateStateMessage(LoadController.java:190)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at com.google.common.eventbus.EventSubscriber.handleEvent(EventSubscriber.java:74)
	at com.google.common.eventbus.SynchronizedEventSubscriber.handleEvent(SynchronizedEventSubscriber.java:47)
	at com.google.common.eventbus.EventBus.dispatch(EventBus.java:322)
	at com.google.common.eventbus.EventBus.dispatchQueuedEvents(EventBus.java:304)
	at com.google.common.eventbus.EventBus.post(EventBus.java:275)
	at cpw.mods.fml.common.LoadController.distributeStateMessage(LoadController.java:119)
	at cpw.mods.fml.common.Loader.initializeMods(Loader.java:737)
	at cpw.mods.fml.client.FMLClientHandler.finishMinecraftLoading(FMLClientHandler.java:311)
	at net.minecraft.client.Minecraft.func_71384_a(Minecraft.java:552)

-- Initialization --
Details:
Stacktrace:
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:878)
	at net.minecraft.client.main.Main.main(SourceFile:148)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)

-- System Details --
Details:
	Minecraft Version: 1.7.10
	Operating System: Mac OS X (x86_64) version 10.10.5
	Java Version: 1.8.0_65, Oracle Corporation
	Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
	Memory: 186368600 bytes (177 MB) / 643301376 bytes (613 MB) up to 954728448 bytes (910 MB)
	JVM Flags: 1 total; -Xmx1G
	AABB Pool Size: 0 (0 bytes; 0 MB) allocated, 0 (0 bytes; 0 MB) used
	IntCache: cache: 0, tcache: 0, allocated: 0, tallocated: 0
	FML: MCP v9.05 FML v7.10.99.99 Minecraft Forge 10.13.4.1448 Naruto Mod 50 mods loaded, 50 mods active
	States: 'U' = Unloaded 'L' = Loaded 'C' = Constructed 'H' = Pre-initialized 'I' = Initialized 'J' = Post-initialized 'A' = Available 'D' = Disabled 'E' = Errored
	UCHI	mcp{9.05} [Minecraft Coder Pack] (minecraft.jar) 
	UCHI	FML{7.10.99.99} [Forge Mod Loader] (minecraftforge-1.7.10-10.13.4.1448.jar) 
	UCHI	Forge{10.13.4.1448} [Minecraft Forge] (minecraftforge-1.7.10-10.13.4.1448.jar) 
	UCHI	Micdoodlecore{} [Micdoodle8 Core] (minecraft.jar) 
	UCHI	TooManyItems{1.7.10} [TooManyItems] (minecraft.jar) 
	UCHI	mod_ThreadedLighting{1.7.10-1.0} [Threaded Lighting] (minecraft.jar) 
	UCHI	gilded-games-util{1.7.10-1.1} [Gilded Games Utility] (gilded-games-util.jar) 
	UCHI	lightsabers{0.7.1} [Advanced Lightsabers Mod] (AdvancedLightsabers-1.7.10-0.7.2.jar) 
	UCHI	adventurebackpack{1.7.10-0.8b} [Adventure Backpack] (adventurebackpack-1.7.10-0.8c.jar) 
	UCHI	aether{Alpha 1.7.10-1.4} [Aether II] (aether.jar) 
	UCHI	AnimationAPI{1.2.4} [AnimationAPI] (AnimationAPI-1.7.10-1.2.4.jar) 
	UCHI	ArchimedesShips{1.7.10 v1.7.1} [Archimedes' Ships] (ArchimedesShips-1.7.1.jar) 
	UCHI	BuildCraft|Core{7.1.14} [BuildCraft] (buildcraft-7.1.14.jar) 
	UCHI	BuildCraft|Builders{7.1.14} [BC Builders] (buildcraft-7.1.14.jar) 
	UCHI	BuildCraft|Transport{7.1.14} [BC Transport] (buildcraft-7.1.14.jar) 
	UCHI	BuildCraft|Energy{7.1.14} [BC Energy] (buildcraft-7.1.14.jar) 
	UCHI	BuildCraft|Silicon{7.1.14} [BC Silicon] (buildcraft-7.1.14.jar) 
	UCHI	BuildCraft|Robotics{7.1.14} [BC Robotics] (buildcraft-7.1.14.jar) 
	UCHI	BuildCraft|Factory{7.1.14} [BC Factory] (buildcraft-7.1.14.jar) 
	UCHI	chocolateQuest{1.0} [Chocolate Quest] (chocolateQuest-1.7.10-1.1d.jar) 
	UCHI	customnpcs{1.7.10} [CustomNpcs] (CustomNPCs_1.7.10.jar) 
	UCHI	DamageIndicatorsMod{3.2.0} [Damage Indicators] (Damage-Indicators-Mod-1.7.10.jar) 
	UCHI	fossil{1.7.10 Build 7.2.1} [Fossils and Archeology Revival] (Fossils_Archeology_Revival-1.7.10_Build-7.2.1.jar) 
	UCHI	GalacticraftCore{3.0.12} [Galacticraft Core] (GalacticraftCore-1.7-3.0.12.375.jar) 
	UCHI	GalacticraftMars{3.0.12} [Galacticraft Planets] (Galacticraft-Planets-1.7-3.0.12.375.jar) 
	UCHI	GraveStone{2.12.2} [GraveStone] (GraveStone-2.12.2.jar) 
	UCHI	iChunUtil{4.2.2} [iChunUtil] (iChunUtil-4.2.2.jar) 
	UCHI	ninjamod{4.0} [The Ninja Mod] (Jond311s-Ninja-Mod-1.7.10.jar) 
	UCHI	jinryuujrmcore{1.1.16} [JinRyuu's JRMCore] (JRMCore-v1.1.16.jar) 
	UCHI	jcanimation{1.2.4} [JCAnimationAPI] (JurassiCraft-1.4.5.jar) 
	UCHI	llibrary{0.3.3} [LLibrary] (LLibrary-0.3.3-1.7.10.jar) 
	UCHI	jurassicraft{1.4.5} [JurassiCraft] (JurassiCraft-1.4.5.jar) 
	UCHI	Mantle{1.7.10-0.3.2.jenkins184} [Mantle] (Mantle-1.7.10-0.3.2.jar) 
	UCHI	mcanm{1.0.001b_1710} [Minecraft Animated] (mcanm-1.0.001b_1710.jar) 
	UCHI	MCEF{0.6} [Minecraft Chromium Embedded Framework] (MCEF-1.7.10-0.7.jar) 
	UCHI	minecraftstorymodemod{2.0.0} [minecraftstorymodemod] (Mincecraftstorymodemodv2.0.0.zip) 
	UCHI	numina{0.4.0.131} [Numina] (Numina-0.4.0.131.jar) 
	UCHI	powersuits{0.11.0.300} [MachineMuse's Modular Powersuits] (ModularPowersuits-0.11.0.300.jar) 
	UCHI	Morph{0.9.2} [Morph] (Morph-Beta-0.9.2.jar) 
	UCHI	mowziesmobs{1.2.5-undefined} [Mowzie's Mobs] (Mowzie's Mobs-1.2.6.jar) 
	UCHI	MutantCreatures{1.4.9} [Mutant Creatures] (MutantCreatures-1.7.10-1.4.9.jar) 
	UCHI	narutomod{0.3.4} [SEKWAH41's Naruto Mod] (Naruto+Mod+v0.3.4c+-+Pre+release.jar) 
	UCHI	AM{0.1} [Alcohol Mod] (NarutoAnimeMod0.2 - Awakening Of The Uchiha Susanoo.jar) 
	UCHI	jinryuunarutoc{0.5.6} [Naruto C] (NarutoC-v0.5.6.jar) 
	UCHE	starwarsmod{1.2.9} [Parzi's Star Wars Mod] (Parzi's Star Wars Mod v1.2.9.jar) 
	UCHI	PortalGun{4.0.0-beta-6} [PortalGun] (PortalGun-4.0.0-beta-6.jar) 
	UCHI	ReiMinimap{1.7.10} [Rei's Minimap] (Reis-Minimap-Mod-1.7.10.jar) 
	UCHI	sus{4.0.10} [Superheroes Unlimited Mod] (Superheroes Unlimited Mod-1.7.10-4.0.10.jar) 
	UCHI	TConstruct{1.7.10-1.8.8.build988} [Tinkers' Construct] (TConstruct-1.7.10-1.8.8.jar) 
	UCHI	TwilightForest{2.3.7} [The Twilight Forest] (twilightforest-1.7.10-2.3.7.jar) 
	GL info: ' Vendor: 'ATI Technologies Inc.' Version: '2.1 ATI-1.32.25' Renderer: 'AMD Radeon HD 6750M OpenGL Engine'
	Mantle Environment: Environment healthy.
	TConstruct Environment: Environment healthy.
	Launched Version: 1.7.10
	LWJGL: 2.9.1
	OpenGL: AMD Radeon HD 6750M OpenGL Engine GL version 2.1 ATI-1.32.25, ATI Technologies Inc.
	GL Caps: Using GL 1.3 multitexturing.
Using framebuffer objects because ARB_framebuffer_object is supported and separate blending is supported.
Anisotropic filtering is supported and maximum anisotropy is 16.
Shaders are available because OpenGL 2.1 is supported.

	Is Modded: Definitely; Client brand changed to 'fml,forge'
	Type: Client (map_client.txt)
	Resource Packs: []
	Current Language: English (US)
	Profiler Position: N/A (disabled)
	Vec3 Pool Size: 0 (0 bytes; 0 MB) allocated, 0 (0 bytes; 0 MB) used
	Anisotropic Filtering: Off (1)

**Comment by INeedSomeHelpPronto** [comment]
nevermind I fixed it
