### ISSUE TITLE
Server Crashing when player log in while wearing a robe

### ISSUE THREAD

**Issue by unrivaledneo** [Parzivail-Modding-Team/ParziStarWarsMod#60]
Server Issue
SW Mod 1.2.10
Cauldron 1.7.10

Server crashes when players log on while wearing a jedi robe.

[15:17:24 ERROR]: Exception caught during firing event cpw.mods.fml.common.gameevent.PlayerEvent$PlayerLoggedOutEvent@3ab98a9e:
java.lang.NullPointerException
at com.parzivail.pswm.jedirobes.ArmorJediRobes.setActive(ArmorJediRobes.java:263) ~[ArmorJediRobes.class:?]
at com.parzivail.pswm.jedirobes.ArmorJediRobes.setActive(ArmorJediRobes.java:258) ~[ArmorJediRobes.class:?]
at com.parzivail.pswm.handlers.CommonEventHandler.resetRobes(CommonEventHandler.java:486) ~[CommonEventHandler.class:?]
at com.parzivail.pswm.handlers.CommonEventHandler.logOut(CommonEventHandler.java:71) ~[CommonEventHandler.class:?]
at cpw.mods.fml.common.eventhandler.ASMEventHandler_8_CommonEventHandler_logOut_PlayerLoggedOutEvent.invoke(.dynamic) ~[?:?]
at cpw.mods.fml.common.eventhandler.ASMEventHandler.invoke(ASMEventHandler.java:54) ~[ASMEventHandler.class:git-Cauldron-MCPC-Plus-1.7.10-1.1236.05.212]
at cpw.mods.fml.common.eventhandler.EventBus.post(EventBus.java:138) [EventBus.class:git-Cauldron-MCPC-Plus-1.7.10-1.1236.05.212]
at cpw.mods.fml.common.FMLCommonHandler.firePlayerLoggedOut(FMLCommonHandler.java:575) [FMLCommonHandler.class:git-Cauldron-MCPC-Plus-1.7.10-1.1236.05.212]
at net.minecraft.server.management.ServerConfigurationManager.disconnect(ServerConfigurationManager.java:433) [oi.class:?]
at net.minecraft.network.NetHandlerPlayServer.func_147231_a(NetHandlerPlayServer.java:974) [nh.class:?]
at net.minecraft.network.NetworkSystem.func_151269_c(NetworkSystem.java:162) [nc.class:?]
at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:980) [MinecraftServer.class:?]
at net.minecraft.server.dedicated.DedicatedServer.func_71190_q(DedicatedServer.java:423) [lt.class:?]
at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:798) [MinecraftServer.class:?]
at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:658) [MinecraftServer.class:?]
at java.lang.Thread.run(Thread.java:745) [?:1.8.0_45-internal]
[15:17:24 ERROR]: Index: 1 Listeners:
[15:17:24 ERROR]: 0: NORMAL
[15:17:24 ERROR]: 1: ASM: com.parzivail.pswm.handlers.CommonEventHandler@3b35791c logOut(Lcpw/mods/fml/common/gameevent/PlayerEvent$PlayerLoggedOutEvent;)V
[15:17:24 ERROR]: Encountered an unexpected exception
java.lang.NullPointerException
at com.parzivail.pswm.jedirobes.ArmorJediRobes.setActive(ArmorJediRobes.java:263) ~[ArmorJediRobes.class:?]
at com.parzivail.pswm.jedirobes.ArmorJediRobes.setActive(ArmorJediRobes.java:258) ~[ArmorJediRobes.class:?]
at com.parzivail.pswm.handlers.CommonEventHandler.resetRobes(CommonEventHandler.java:486) ~[CommonEventHandler.class:?]
at com.parzivail.pswm.handlers.CommonEventHandler.logOut(CommonEventHandler.java:71) ~[CommonEventHandler.class:?]
at cpw.mods.fml.common.eventhandler.ASMEventHandler_8_CommonEventHandler_logOut_PlayerLoggedOutEvent.invoke(.dynamic) ~[?:?]
at cpw.mods.fml.common.eventhandler.ASMEventHandler.invoke(ASMEventHandler.java:54) ~[ASMEventHandler.class:git-Cauldron-MCPC-Plus-1.7.10-1.1236.05.212]
at cpw.mods.fml.common.eventhandler.EventBus.post(EventBus.java:138) ~[EventBus.class:git-Cauldron-MCPC-Plus-1.7.10-1.1236.05.212]
at cpw.mods.fml.common.FMLCommonHandler.firePlayerLoggedOut(FMLCommonHandler.java:575) ~[FMLCommonHandler.class:git-Cauldron-MCPC-Plus-1.7.10-1.1236.05.212]
at net.minecraft.server.management.ServerConfigurationManager.disconnect(ServerConfigurationManager.java:433) ~[oi.class:?]
at net.minecraft.

network.NetHandlerPlayServer.func_147231_a(NetHandlerPlayServer.java:974) ~[nh.class:?]
at net.minecraft.network.NetworkSystem.func_151269_c(NetworkSystem.java:162) ~[nc.class:?]
at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:980) ~[MinecraftServer.class:?]
at net.minecraft.server.dedicated.DedicatedServer.func_71190_q(DedicatedServer.java:423) ~[lt.class:?]
at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:798) ~[MinecraftServer.class:?]
at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:658) [MinecraftServer.class:?]
at java.lang.Thread.run(Thread.java:745) [?:1.8.0_45-internal]

**Comment by parzivail** [comment]
Yikes! I'll get on it soon.

**Comment by parzivail** [comment]
Fixed in 1.2.11
