### ISSUE TITLE
I can't make a server

### ISSUE THREAD

**Issue by Rainblade** [Parzivail-Modding-Team/ParziStarWarsMod#63]
I have tried everything but the forge server just crashes. The minecraft server option works but my client crashes every time I use something from the mod. Please help me <3

**Comment by Rainblade** [comment]
I rally like this mod and would love to okay with my friends

**Comment by Rainblade** [comment]
Really*

**Comment by Alexismachina** [comment]
@Rainblade You need to give a crashlog for any of us to help and you need to make a crash report ressembling this : 
Mod Version (i.e. 1.2.6)
A brief description of what you were doing when it crashed (i.e. I right-clicked on a Moisture Vaporator)
Client or server? (Client or Server)
If the above answer was Server, please provide your server information (i.e. Forge, Cauldron, etc.)
Crash report (NOT the log! We need the contents of the file Minecraft generated when it crashed, found under .minecraft/crash-reports)

**Comment by Rainblade** [comment]
Ok

**Comment by Rainblade** [comment]
---- Minecraft Crash Report ----
// I bet Cylons wouldn't have this problem.

Time: 19/03/16 12:00
Description: Exception in server tick loop

java.lang.NoClassDefFoundError: Lnet/minecraftforge/common/config/Configuration;
	at java.lang.Class.getDeclaredFields0(Native Method)
	at java.lang.Class.privateGetDeclaredFields(Unknown Source)
	at java.lang.Class.getDeclaredField(Unknown Source)
	at cpw.mods.fml.common.ProxyInjector.inject(ProxyInjector.java:43)
	at cpw.mods.fml.common.FMLModContainer.constructMod(FMLModContainer.java:492)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at com.google.common.eventbus.EventSubscriber.handleEvent(EventSubscriber.java:74)
	at com.google.common.eventbus.SynchronizedEventSubscriber.handleEvent(SynchronizedEventSubscriber.java:47)
	at com.google.common.eventbus.EventBus.dispatch(EventBus.java:322)
	at com.google.common.eventbus.EventBus.dispatchQueuedEvents(EventBus.java:304)
	at com.google.common.eventbus.EventBus.post(EventBus.java:275)
	at cpw.mods.fml.common.LoadController.sendEventToModContainer(LoadController.java:208)
	at cpw.mods.fml.common.LoadController.propogateStateMessage(LoadController.java:187)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at com.google.common.eventbus.EventSubscriber.handleEvent(EventSubscriber.java:74)
	at com.google.common.eventbus.SynchronizedEventSubscriber.handleEvent(SynchronizedEventSubscriber.java:47)
	at com.google.common.eventbus.EventBus.dispatch(EventBus.java:322)
	at com.google.common.eventbus.EventBus.dispatchQueuedEvents(EventBus.java:304)
	at com.google.common.eventbus.EventBus.post(EventBus.java:275)
	at cpw.mods.fml.common.LoadController.distributeStateMessage(LoadController.java:118)
	at cpw.mods.fml.common.Loader.loadMods(Loader.java:492)
	at cpw.mods.fml.server.FMLServerHandler.beginServerLoading(FMLServerHandler.java:87)
	at cpw.mods.fml.common.FMLCommonHandler.onServerStart(FMLCommonHandler.java:314)
	at net.minecraft.server.dedicated.DedicatedServer.func_71197_b(DedicatedServer.java:117)
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:400)
	at net.minecraft.server.MinecraftServer$2.run(MinecraftServer.java:693)
Caused by: java.lang.ClassNotFoundException: net.minecraftforge.common.config.Configuration
	at net.minecraft.launchwrapper.LaunchClassLoader.findClass(LaunchClassLoader.java:191)
	at java.lang.ClassLoader.loadClass(Unknown Source)
	at java.lang.ClassLoader.loadClass(Unknown Source)
	... 32 more
Caused by: java.lang.NullPointerException
	at net.minecraft.launchwrapper.LaunchClassLoader.findClass(LaunchClassLoader.java:182)
	... 34 more


A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- System Details --
Details:
	Minecraft Version: 1.7.10
	Operating System: Windows 8.1 (x86) version 6.3
	Java Version: 1.8.0_73, Oracle Corporation
	Java VM Version: Java HotSpot(TM) Client VM (mixed mode), Oracle Corporation
	Memory: 31561888 bytes (30 MB) / 71385088 bytes (68 MB) up to 259522560 bytes (247 MB)
	JVM Flags: 0 total; 
	AABB Pool Size: 0 (0 bytes; 0 MB) allocated, 0 (0 bytes; 0 MB) used
	IntCache: cache: 0, tcache: 0, allocated: 0, tallocated: 0
	FML: MCP v9.05 FML v7.10.88.1024 3 mods loaded, 3 mods active
	mcp{9.05} [Minecraft Coder Pack] (minecraft.jar) Unloaded->Constructed
	FML{7.10.88.1024} [Forge Mod Loader] (fml-1.7.10-7.10.88.1024-universal.jar) Unloaded->Constructed
	starwarsmod{1.2.10} [Parzi's Star Wars Mod] (Parzi's Star Wars Mod v1.2.10.jar) Unloaded
	Profiler Position: N/A (disabled)
	Is Modded: Definitely; Server brand changed to 'fml'
	Type: Dedicated Server (map_server.txt)

**Comment by Rainblade** [comment]
Server 
forge 1.2.10
crashes instantly as soon as the java program opens

**Comment by Rainblade** [comment]
@Alexismachina

**Comment by Rainblade** [comment]
1.2.10 is the mod version

**Comment by Alexismachina** [comment]
What's the forge version?

**Comment by Rainblade** [comment]
1.7.10 recommended

**Comment by Alexismachina** [comment]
update to 1614

**Comment by Rainblade** [comment]
Okay I'll try it

**Comment by Rainblade** [comment]
Thank you so much it works

**Comment by Rainblade** [comment]
I need to allocate memory to the server without making it cmd @Alexismachina

**Comment by parzivail** [comment]
Can you run a batch/shell file?

**Comment by Rainblade** [comment]
I have tried but then I cannot connect to it I'm using hamachi

**Comment by parzivail** [comment]
@Rainblade That shouldn't be an issue for hamachi, what parameters are you running it with?

**Comment by Rainblade** [comment]
What are parameters?

**Comment by parzivail** [comment]
like, when you set how much memory to use and stuff

**Comment by Rainblade** [comment]
I have finally figured it out I am a mega derp, my firewalls were blocking Java and the network so hamachi couldn't work @parzivail

**Comment by Rainblade** [comment]
Also for those who have Java 8 and it creeps crashing its a bug you need to downgrade to 7 and make sure the path for the server leads to Java 7 not 8 <3

**Comment by parzivail** [comment]
I'm glad you found a fix but unfortunately the mod requires Java 8 to
functiom correctly, it uses features that Java 7 doesn't have for networking

**Comment by Rainblade** [comment]
Okay
