### ISSUE TITLE
Force Use Crash

### ISSUE THREAD

**Issue by IISithBoi** [Parzivail-Modding-Team/ParziStarWarsMod#77]
So. I'm playing in my world, I'd try to use my next Force Move on my Robe, then it Shut down the Server with this note.
---- Minecraft Crash Report ----
// You're mean.

Time: 26/08/16 18:02
Description: Unexpected error

java.lang.NullPointerException: Unexpected error
	at com.parzivail.pswm.handlers.CommonEventHandler.onKeyInput(CommonEventHandler.java:282)
	at cpw.mods.fml.common.eventhandler.ASMEventHandler_19_CommonEventHandler_onKeyInput_KeyInputEvent.invoke(.dynamic)
	at cpw.mods.fml.common.eventhandler.ASMEventHandler.invoke(ASMEventHandler.java:54)
	at cpw.mods.fml.common.eventhandler.EventBus.post(EventBus.java:138)
	at cpw.mods.fml.common.FMLCommonHandler.fireKeyInput(FMLCommonHandler.java:540)
	at net.minecraft.client.Minecraft.func_71407_l(Minecraft.java:1873)
	at net.minecraft.client.Minecraft.func_71411_J(Minecraft.java:973)
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:898)
	at net.minecraft.client.main.Main.main(SourceFile:148)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:483)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Stacktrace:
	at com.parzivail.pswm.handlers.CommonEventHandler.onKeyInput(CommonEventHandler.java:282)
	at cpw.mods.fml.common.eventhandler.ASMEventHandler_19_CommonEventHandler_onKeyInput_KeyInputEvent.invoke(.dynamic)
	at cpw.mods.fml.common.eventhandler.ASMEventHandler.invoke(ASMEventHandler.java:54)
	at cpw.mods.fml.common.eventhandler.EventBus.post(EventBus.java:138)
	at cpw.mods.fml.common.FMLCommonHandler.fireKeyInput(FMLCommonHandler.java:540)

-- Affected level --
Details:
	Level name: MpServer
	All players: 1 total; [EntityClientPlayerMP['IISithBoi'/195, l='MpServer', x=-14.06, y=63.62, z=10.24]]
	Chunk stats: MultiplayerChunkCache: 121, 121
	Level seed: 0
	Level generator: ID 00 - default, ver 1. Features enabled: false
	Level generator options: 
	Level spawn location: World: (8,64,8), Chunk: (at 8,4,8 in 0,0; contains blocks 0,0,0 to 15,255,15), Region: (0,0; contains chunks 0,0 to 31,31, blocks 0,0,0 to 511,255,511)
	Level time: 457342 game time, 466677 day time
	Level dimension: 0
	Level storage version: 0x00000 - Unknown?
	Level weather: Rain time: 0 (now: false), thunder time: 0 (now: false)
	Level game mode: Game mode: survival (ID 0). Hardcore: false. Cheats: false
	Forced entities: 27 total; [EntityCreeper['Creeper'/22983, l='MpServer', x=31.41, y=43.00, z=-35.66], EntityCreeper['Creeper'/22984, l='MpServer', x=39.03, y=41.00, z=-30.56], EntityCreeper['Creeper'/22985, l='MpServer', x=33.13, y=43.00, z=-35.25], EntitySkeleton['Skeleton'/22986, l='MpServer', x=26.44, y=47.00, z=-35.00], EntityChicken['Chicken'/74, l='MpServer', x=-84.53, y=66.00, z=8.34], EntityZombie['Zombie'/22859, l='MpServer', x=-20.50, y=16.00, z=-45.50], EntityItemFrame['entity.ItemFrame.name'/140, l='MpServer', x=-14.50, y=64.50, z=5.06], EntityChicken['Chicken'/76, l='MpServer', x=-88.53, y=68.00, z=13.59], EntityClientPlayerMP['IISithBoi'/195, l='MpServer', x=-14.06, y=63.62, z=10.24], EntityChicken['Chicken'/99, l='MpServer', x=-78.69, y=64.00, z=5.34], EntityChicken['Chicken'/100, l='MpServer', x=-65.47, y=64.00, z=4.59], EntityItem['item.item.rottenFlesh'/16293, l='MpServer', x=-1.72, y=64.13, z=37.81], EntityItem['item.tile.dirt.default'/22757, l='MpServer', x=-2.31, y=63.13, z=15.34], EntityBat['Bat'/23078, l='MpServer', x=-72.66, y=29.00, z=-60.64], EntityItem['item.tile.dirt.default'/22759, l='MpServer', x=-2.00, y=63.13, z=14.22], EntityBat['Bat'/23079, l='MpServer', x=-62.38, y=45.00, z=-61.46], EntityBat['Bat'/23082, l='MpServer', x=-71.54, y=48.26, z=-51.51], EntityWitch['Witch'/22828, l='MpServer', x=48.06, y=19.00, z=-61.50], EntityItem['item.item.egg'/16685, l='MpServer', x=-62.66, y=64.13, z=4.59], EntityChicken['Chicken'/111, l='MpServer', x=-63.53, y=64.00, z=3.59], EntityZombie['Zombie'/22127, l='MpServer', x=39.54, y=-1252.35, z=42.94], EntityZombie['Zombie'/22255, l='MpServer', x=55.50, y=14.00, z=33.50], EntityCreeper['Creeper'/23343, l='MpServer', x=49.50, y=21.00, z=-60.50], EntityChicken['Chicken'/112, l='MpServer', x=-60.47, y=64.00, z=9.47], EntityZombie['Zombie'/22768, l='MpServer', x=35.50, y=20.00, z=-66.50], EntityWitch['Witch'/22450, l='MpServer', x=42.50, y=16.00, z=70.50], EntityZombie['Zombie'/22844, l='MpServer', x=-78.72, y=13.00, z=-44.91]]
	Retry entities: 0 total; []
	Server brand: fml,forge
	Server type: Integrated singleplayer server
Stacktrace:
	at net.minecraft.client.multiplayer.WorldClient.func_72914_a(WorldClient.java:373)
	at net.minecraft.client.Minecraft.func_71396_d(Minecraft.java:2444)
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:927)
	at net.minecraft.client.main.Main.main(SourceFile:148)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:483)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)

-- System Details --
Details:
	Minecraft Version: 1.7.10
	Operating System: Windows 10 (amd64) version 10.0
	Java Version: 1.8.0_25, Oracle Corporation
	Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
	Memory: 291606320 bytes (278 MB) / 637640704 bytes (608 MB) up to 1060372480 bytes (1011 MB)
	JVM Flags: 6 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xmx1G -XX:+UseConcMarkSweepGC -XX:+CMSIncrementalMode -XX:-UseAdaptiveSizePolicy -Xmn128M
	AABB Pool Size: 0 (0 bytes; 0 MB) allocated, 0 (0 bytes; 0 MB) used
	IntCache: cache: 0, tcache: 0, allocated: 13, tallocated: 95
	FML: MCP v9.05 FML v7.10.99.99 Minecraft Forge 10.13.4.1481 6 mods loaded, 6 mods active
	States: 'U' = Unloaded 'L' = Loaded 'C' = Constructed 'H' = Pre-initialized 'I' = Initialized 'J' = Post-initialized 'A' = Available 'D' = Disabled 'E' = Errored
	UCHIJAAAA	mcp{9.05} [Minecraft Coder Pack] (minecraft.jar) 
	UCHIJAAAA	FML{7.10.99.99} [Forge Mod Loader] (forge-1.7.10-10.13.4.1481-1.7.10.jar) 
	UCHIJAAAA	Forge{10.13.4.1481} [Minecraft Forge] (forge-1.7.10-10.13.4.1481-1.7.10.jar) 
	UCHIJAAAA	CodeChickenCore{1.0.7.47} [CodeChicken Core] (minecraft.jar) 
	UCHIJAAAA	NotEnoughItems{1.0.5.120} [Not Enough Items] (NotEnoughItems-1.7.10-1.0.5.120-universal.jar) 
	UCHIJAAAA	starwarsmod{1.3.3} [Parzi's Star Wars Mod] (Parzi's Star Wars Mod v1.3.3.jar) 
	GL info: ' Vendor: 'Intel' Version: '4.0.0 - Build 10.18.10.4276' Renderer: 'Intel(R) HD Graphics'
	Launched Version: 1.7.10-Forge10.13.4.1481-1.7.10
	LWJGL: 2.9.1
	OpenGL: Intel(R) HD Graphics GL version 4.0.0 - Build 10.18.10.4276, Intel
	GL Caps: Using GL 1.3 multitexturing.
Using framebuffer objects because OpenGL 3.0 is supported and separate blending is supported.
Anisotropic filtering is supported and maximum anisotropy is 16.
Shaders are available because OpenGL 2.1 is supported.

	Is Modded: Definitely; Client brand changed to 'fml,forge'
	Type: Client (map_client.txt)
	Resource Packs: []
	Current Language: English (UK)
	Profiler Position: N/A (disabled)
	Vec3 Pool Size: 0 (0 bytes; 0 MB) allocated, 0 (0 bytes; 0 MB) used
	Anisotropic Filtering: Off (1)

**Comment by parzivail** [comment]
Please read our post about where to post issues henceforth and post there instead.
